"""Healthcare-specific enrichments, conditions, swaps, and extra recipes."""

# 8 recommended conditions surfaced on the Healthcare entry screen
CONDITIONS = [
    {"id": "heart-disease", "label": "Heart Health",
     "icon": "Heart", "blurb": "Omega-3 rich, low-sodium meals.",
     "image": "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600"},
    {"id": "diabetes", "label": "Diabetes",
     "icon": "Activity", "blurb": "Low-GI, high-fibre balance.",
     "image": "https://images.unsplash.com/photo-1547592180-85f173990554?w=600"},
    {"id": "thyroid", "label": "Thyroid",
     "icon": "Sparkles", "blurb": "Selenium, iodine-balanced foods.",
     "image": "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=600"},
    {"id": "pcos", "label": "PCOS",
     "icon": "Flower2", "blurb": "Insulin-friendly, anti-inflammatory.",
     "image": "https://images.unsplash.com/photo-1517093602195-b40af9688b4e?w=600"},
    {"id": "weight-management", "label": "Weight Management",
     "icon": "Scale", "blurb": "High-protein, satiating, calorie-aware.",
     "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600"},
    {"id": "hypertension", "label": "Blood Pressure",
     "icon": "Gauge", "blurb": "DASH-aligned, sodium under 500mg.",
     "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600"},
    {"id": "gut-health", "label": "Gut Health",
     "icon": "Leaf", "blurb": "Fermented foods + soluble fibre.",
     "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600"},
    {"id": "immunity", "label": "Immunity",
     "icon": "Shield", "blurb": "Vit C, zinc, antioxidants.",
     "image": "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600"},
]

# Per-recipe enrichments — keyed by existing seed_data recipe id
ENRICHMENTS = {
    "hc-001": {
        "meal_type": "lunch", "prep_minutes": 30,
        "health_scores": ["diabetes-safe", "heart-friendly", "anti-inflammatory"],
        "nutritional_tags": ["low-sodium", "low-GI", "high-fibre", "anti-inflammatory"],
        "why_this_works": {
            "diabetes": "Low GI (32) and 12g fibre keep blood sugar stable for hours.",
            "heart-disease": "No saturated fat, turmeric is anti-inflammatory, sodium under 200mg.",
            "hypertension": "Sodium 180mg — well within DASH guidelines.",
        },
    },
    "hc-002": {
        "meal_type": "dinner", "prep_minutes": 25,
        "health_scores": ["heart-friendly", "thyroid-supportive", "post-surgery-safe"],
        "nutritional_tags": ["omega-3", "high-protein", "low-sodium", "gluten-free"],
        "why_this_works": {
            "heart-disease": "Rich in omega-3 (EPA/DHA) — reduces triglycerides; sodium just 95mg.",
            "thyroid": "Selenium from salmon supports T4→T3 conversion.",
            "post-surgery": "34g lean protein speeds tissue repair; easy to digest.",
        },
    },
    "hc-003": {
        "meal_type": "lunch", "prep_minutes": 20,
        "health_scores": ["kidney-friendly", "heart-friendly"],
        "nutritional_tags": ["low-potassium", "low-sodium", "plant-based", "gluten-free"],
        "why_this_works": {
            "kidney-disease": "Avoids high-potassium veg (no spinach/tomato); sodium under 30mg.",
            "hypertension": "Plant-based, fibre-rich; supports BP control.",
            "weight-management": "290 kcal, 9g protein, 6g fibre — satiating without spike.",
        },
    },
    "hc-004": {
        "meal_type": "breakfast", "prep_minutes": 5,
        "health_scores": ["diabetes-safe", "pcos-friendly"],
        "nutritional_tags": ["high-fibre", "low-GI", "plant-based", "anti-inflammatory"],
        "why_this_works": {
            "pcos": "13g fibre + chia omega-3 reduce insulin resistance markers.",
            "diabetes": "GI 40 — overnight soak lowers carbs' impact on glucose curve.",
            "weight-management": "Slow-release carbs; cinnamon helps glucose disposal.",
        },
    },
    "hc-005": {
        "meal_type": "dinner", "prep_minutes": 35,
        "health_scores": ["gentle-on-gut", "post-surgery-safe"],
        "nutritional_tags": ["soft-texture", "easy-digest", "vegetarian"],
        "why_this_works": {
            "elderly-nutrition": "Soft, mashable, complete protein from rice + dal combo.",
            "post-surgery": "Low fibre when needed, high digestibility, gentle spicing.",
            "gut-health": "Bland, easy-on-stomach for IBS or GERD flares.",
        },
    },
}

# Additional healthcare recipes covering breakfast/lunch/dinner/snacks across conditions
def _ing(name, amount, q=None):
    qstr = (q or name).split(",")[0].strip().replace(" ", "+")
    return {"name": name, "amount": amount,
            "image": f"https://source.unsplash.com/120x120/?{qstr},food,ingredient"}


EXTRA_RECIPES = [
    {
        "id": "hc-006", "title": "Beetroot & Apple Detox Smoothie",
        "category": "healthcare",
        "conditions": ["heart-disease", "hypertension", "immunity", "weight-management"],
        "country": "International", "region": "Wellness",
        "image": "https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800",
        "video_url": "https://www.youtube.com/embed/8YFYeGfX8jE",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 5, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "drink"],
        "description": "Nitrate-rich beet smoothie that gently lowers blood pressure.",
        "ingredients": [
            _ing("Cooked beetroot", "120g", "beetroot"),
            _ing("Green apple", "1 medium", "apple"),
            _ing("Fresh ginger", "1 tsp", "ginger"),
            _ing("Lemon juice", "1 tbsp", "lemon"),
            _ing("Cold water", "200ml", "water"),
        ],
        "steps": [
            "Blend everything until smooth.",
            "Strain if you prefer a thin texture.",
            "Serve immediately for best nutrient retention.",
        ],
        "nutrition": {"calories": 130, "protein": 2, "carbs": 30, "fat": 0, "fiber": 6, "sodium": 90, "gi": 38},
        "_enrichment": {
            "meal_type": "snack", "prep_minutes": 5,
            "health_scores": ["heart-friendly", "diabetes-safe", "immunity-boost"],
            "nutritional_tags": ["nitrate-rich", "low-sodium", "antioxidant", "low-calorie"],
            "why_this_works": {
                "hypertension": "Dietary nitrates from beets convert to NO, lowering systolic BP by ~4-5 mmHg.",
                "heart-disease": "Polyphenols + zero saturated fat support endothelial health.",
                "immunity": "Vit C from apple + lemon, plus betalains, support immune cells.",
            },
        },
    },
    {
        "id": "hc-007", "title": "Greek Yogurt with Walnuts & Honey",
        "category": "healthcare",
        "conditions": ["gut-health", "thyroid", "weight-management", "pcos"],
        "country": "Greece", "region": "Mediterranean",
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800",
        "video_url": "https://www.youtube.com/embed/3F9LkEX5xqQ",
        "cuisine": "Greek", "difficulty": "Easy", "cook_time": 3, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian", "high-protein", "snack"],
        "description": "Probiotic-rich Greek yogurt with omega-3 walnuts.",
        "ingredients": [
            _ing("Greek yogurt (full-fat)", "200g", "greek+yogurt"),
            _ing("Walnuts, chopped", "20g", "walnut"),
            _ing("Raw honey", "1 tsp", "honey"),
            _ing("Cinnamon", "1/4 tsp", "cinnamon"),
        ],
        "steps": [
            "Spoon yogurt into a bowl.",
            "Top with walnuts, honey, and a pinch of cinnamon.",
        ],
        "nutrition": {"calories": 280, "protein": 18, "carbs": 14, "fat": 16, "fiber": 2, "sodium": 70, "gi": 35},
        "_enrichment": {
            "meal_type": "snack", "prep_minutes": 3,
            "health_scores": ["gut-friendly", "pcos-friendly"],
            "nutritional_tags": ["probiotic", "high-protein", "omega-3"],
            "why_this_works": {
                "gut-health": "Live cultures (L. acidophilus, Bifidobacterium) support microbiome diversity.",
                "thyroid": "Selenium from walnuts + tyrosine from yogurt aid thyroid hormone production.",
                "pcos": "High protein + healthy fat keeps insulin steady; cinnamon further sensitises.",
            },
        },
    },
    {
        "id": "hc-008", "title": "Spinach & Egg Scramble",
        "category": "healthcare",
        "conditions": ["weight-management", "heart-disease", "immunity", "thyroid"],
        "country": "International", "region": "International",
        "image": "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800",
        "video_url": "https://www.youtube.com/embed/PUP7U5vTMM0",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 8, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian", "high-protein", "gluten-free"],
        "description": "12-minute breakfast: complete protein + leafy greens.",
        "ingredients": [
            _ing("Eggs", "2 large", "egg"),
            _ing("Baby spinach", "60g", "spinach"),
            _ing("Olive oil", "1 tsp", "olive+oil"),
            _ing("Garlic, minced", "1 clove", "garlic"),
            _ing("Black pepper", "1/4 tsp", "pepper"),
        ],
        "steps": [
            "Heat 1 tsp olive oil in non-stick pan.",
            "Saute garlic 20 sec, add spinach, wilt 1 min.",
            "Whisk eggs with pepper, pour over spinach.",
            "Stir gently until curds form, 2 min. Serve.",
        ],
        "nutrition": {"calories": 220, "protein": 16, "carbs": 4, "fat": 15, "fiber": 2, "sodium": 160, "gi": 0},
        "_enrichment": {
            "meal_type": "breakfast", "prep_minutes": 8,
            "health_scores": ["heart-friendly", "thyroid-supportive", "immunity-boost"],
            "nutritional_tags": ["high-protein", "iron-rich", "low-carb", "vit-A"],
            "why_this_works": {
                "weight-management": "16g protein keeps you full till lunch; only 220 kcal.",
                "thyroid": "Iodine + selenium from eggs support thyroid hormone synthesis.",
                "immunity": "Vit A + folate from spinach, complete protein from eggs.",
            },
        },
    },
    {
        "id": "hc-009", "title": "Roasted Chickpea Crunch",
        "category": "healthcare",
        "conditions": ["weight-management", "diabetes", "gut-health", "pcos"],
        "country": "Mediterranean", "region": "Mediterranean",
        "image": "https://images.unsplash.com/photo-1559054663-e8d23213f55c?w=800",
        "video_url": "https://www.youtube.com/embed/sPHbEJTVlIM",
        "cuisine": "Mediterranean", "difficulty": "Easy", "cook_time": 30, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "snack", "high-protein"],
        "description": "Crunchy savoury snack — replaces chips, doubles as salad topper.",
        "ingredients": [
            _ing("Cooked chickpeas, drained", "400g", "chickpeas"),
            _ing("Olive oil", "1 tbsp", "olive+oil"),
            _ing("Smoked paprika", "1 tsp", "paprika"),
            _ing("Cumin powder", "1/2 tsp", "cumin"),
            _ing("Garlic powder", "1/2 tsp", "garlic"),
            _ing("Sea salt", "1/4 tsp", "salt"),
        ],
        "steps": [
            "Preheat oven to 200°C.",
            "Pat chickpeas very dry. Toss with oil + spices.",
            "Spread on tray, roast 25-30 min, shaking halfway.",
            "Cool 5 min for max crunch.",
        ],
        "nutrition": {"calories": 180, "protein": 9, "carbs": 22, "fat": 6, "fiber": 7, "sodium": 240, "gi": 28},
        "_enrichment": {
            "meal_type": "snack", "prep_minutes": 30,
            "health_scores": ["diabetes-safe", "gut-friendly", "pcos-friendly"],
            "nutritional_tags": ["high-fibre", "low-GI", "plant-protein"],
            "why_this_works": {
                "diabetes": "GI 28 — slow-release carbs; 7g fibre slows glucose absorption.",
                "gut-health": "Resistant starch + fibre feed beneficial gut bacteria.",
                "weight-management": "180 kcal · 9g protein · 7g fibre — guilt-free crunch.",
            },
        },
    },
    {
        "id": "hc-010", "title": "Lemon Ginger Wellness Tea",
        "category": "healthcare",
        "conditions": ["immunity", "gut-health", "thyroid"],
        "country": "International", "region": "Wellness",
        "image": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800",
        "video_url": "https://www.youtube.com/embed/IBgJ-XnX-9c",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 5, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "drink"],
        "description": "5-minute zero-calorie immunity drink.",
        "ingredients": [
            _ing("Fresh ginger", "10g sliced", "ginger"),
            _ing("Lemon", "1/2", "lemon"),
            _ing("Raw honey", "1 tsp", "honey"),
            _ing("Hot water", "300ml", "water"),
        ],
        "steps": [
            "Steep ginger in hot water 4 min.",
            "Add lemon juice and honey; stir.",
        ],
        "nutrition": {"calories": 30, "protein": 0, "carbs": 8, "fat": 0, "fiber": 0, "sodium": 5, "gi": 0},
        "_enrichment": {
            "meal_type": "snack", "prep_minutes": 5,
            "health_scores": ["immunity-boost", "gut-friendly"],
            "nutritional_tags": ["antioxidant", "low-calorie", "anti-inflammatory"],
            "why_this_works": {
                "immunity": "Gingerols + Vit C from lemon support white blood cell function.",
                "gut-health": "Soothes nausea, supports digestive enzymes.",
                "thyroid": "Caffeine-free, won't interfere with thyroid medication.",
            },
        },
    },
    {
        "id": "hc-011", "title": "Quinoa Tabbouleh with Mint",
        "category": "healthcare",
        "conditions": ["weight-management", "heart-disease", "diabetes", "gut-health"],
        "country": "Lebanon", "region": "Mediterranean",
        "image": "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800",
        "video_url": "https://www.youtube.com/embed/7xHxQ9XLn2g",
        "cuisine": "Lebanese", "difficulty": "Easy", "cook_time": 15, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "high-protein"],
        "description": "Cold-prep lunch in 15 minutes — fresh, filling, plant-forward.",
        "ingredients": [
            _ing("Cooked quinoa", "200g", "quinoa"),
            _ing("Cucumber, diced", "1/2", "cucumber"),
            _ing("Cherry tomatoes, halved", "150g", "tomato"),
            _ing("Fresh parsley, chopped", "30g", "parsley"),
            _ing("Fresh mint", "10g", "mint"),
            _ing("Lemon juice", "2 tbsp", "lemon"),
            _ing("Olive oil", "1 tbsp", "olive+oil"),
        ],
        "steps": [
            "Combine quinoa, cucumber, tomatoes, parsley, mint.",
            "Whisk lemon juice with olive oil; toss with salad.",
            "Chill 10 min for flavours to meld.",
        ],
        "nutrition": {"calories": 260, "protein": 8, "carbs": 36, "fat": 9, "fiber": 6, "sodium": 60, "gi": 45},
        "_enrichment": {
            "meal_type": "lunch", "prep_minutes": 15,
            "health_scores": ["heart-friendly", "diabetes-safe", "gut-friendly"],
            "nutritional_tags": ["high-fibre", "plant-protein", "low-sodium"],
            "why_this_works": {
                "weight-management": "Filling 260 kcal lunch with 6g fibre and 8g protein.",
                "heart-disease": "Quinoa lignans + olive oil support cholesterol balance.",
                "diabetes": "Quinoa GI 45, cucumber zero — smooth glucose curve.",
            },
        },
    },
    {
        "id": "hc-012", "title": "Sweet Potato & Black Bean Bowl",
        "category": "healthcare",
        "conditions": ["heart-disease", "diabetes", "gut-health", "weight-management"],
        "country": "USA", "region": "International",
        "image": "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800",
        "video_url": "https://www.youtube.com/embed/TSVw6MrlR-w",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 35, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "high-protein"],
        "description": "Plant-protein dinner that supports heart, gut, and steady energy.",
        "ingredients": [
            _ing("Sweet potato, cubed", "300g", "sweet+potato"),
            _ing("Black beans, cooked", "240g", "black+beans"),
            _ing("Avocado", "1/2", "avocado"),
            _ing("Lime juice", "1 tbsp", "lime"),
            _ing("Cumin powder", "1 tsp", "cumin"),
            _ing("Olive oil", "1 tbsp", "olive+oil"),
            _ing("Fresh cilantro", "10g", "cilantro"),
        ],
        "steps": [
            "Roast sweet potato with olive oil + cumin at 200°C for 25 min.",
            "Warm black beans.",
            "Plate sweet potato, beans, sliced avocado.",
            "Drizzle lime, top with cilantro.",
        ],
        "nutrition": {"calories": 410, "protein": 14, "carbs": 56, "fat": 14, "fiber": 14, "sodium": 220, "gi": 50},
        "_enrichment": {
            "meal_type": "dinner", "prep_minutes": 35,
            "health_scores": ["heart-friendly", "diabetes-safe", "gut-friendly"],
            "nutritional_tags": ["high-fibre", "potassium-rich", "plant-protein"],
            "why_this_works": {
                "heart-disease": "Soluble fibre from beans lowers LDL; avocado adds heart-healthy fat.",
                "diabetes": "Resistant starch + 14g fibre = controlled glucose response.",
                "gut-health": "Prebiotic fibre feeds gut microbiome; supports short-chain fatty acid production.",
            },
        },
    },
]


# Smart ingredient swaps — surfaced inside Healthcare hub
SWAPS = [
    {"from": "Sugar", "to": "Dates / Maple syrup", "reason": "Lower GI, adds fibre & minerals.", "best_for": ["diabetes", "pcos"]},
    {"from": "Cream", "to": "Greek yogurt", "reason": "1/3 the saturated fat, double the protein.", "best_for": ["heart-disease", "weight-management"]},
    {"from": "Frying", "to": "Air-fry / Bake", "reason": "Cuts oil by 70-80% with similar crisp.", "best_for": ["heart-disease", "weight-management", "hypertension"]},
    {"from": "Salt", "to": "Lemon + herbs", "reason": "Brightens flavour without sodium.", "best_for": ["hypertension", "kidney-disease"]},
    {"from": "White rice", "to": "Quinoa / Brown rice", "reason": "Lower GI, more fibre & protein.", "best_for": ["diabetes", "pcos"]},
    {"from": "Butter", "to": "Olive oil / Avocado", "reason": "Monounsaturated fats over saturated.", "best_for": ["heart-disease"]},
    {"from": "Soda", "to": "Sparkling water + lemon", "reason": "Zero sugar, same fizz.", "best_for": ["diabetes", "weight-management"]},
    {"from": "Wheat flour", "to": "Almond / Chickpea flour", "reason": "Higher protein, lower GI.", "best_for": ["diabetes", "pcos"]},
]
