"""Healthcare-specific enrichments, conditions, swaps, and extra recipes."""

# All supported conditions across 10 categories.
# priority: 1=critical (always wins conflicts), 2=moderate, 3=lifestyle
# conflict_group: conditions in same group may conflict on macros
# keywords: used for search matching
CONDITIONS = [
    # ── Metabolic / Hormonal ──────────────────────────────────────────────────
    {
        "id": "diabetes", "label": "Diabetes (Type 2)",
        "category": "metabolic", "icon": "Activity", "priority": 1,
        "conflict_group": "blood-sugar",
        "blurb": "Low-GI, high-fibre balance to manage blood glucose.",
        "keywords": ["diabetes", "type 2", "diabetic", "blood sugar", "glucose"],
        "image": "https://images.unsplash.com/photo-1547592180-85f173990554?w=600",
        "foods_to_eat": ["oats", "lentils", "leafy greens", "cinnamon", "berries", "quinoa", "chickpeas"],
        "foods_to_avoid": ["white rice", "white bread", "sugary drinks", "fruit juice", "candy", "refined flour"],
        "food_rules": [
            "Choose low-GI foods — lentils, oats, most vegetables.",
            "Pair every carb with protein or healthy fat to slow glucose rise.",
            "Eat consistent meals every 3-4 hours — no skipping.",
            "Limit sugar to <25g/day; always prefer whole fruit over juice.",
        ],
    },
    {
        "id": "diabetes-t1", "label": "Diabetes (Type 1)",
        "category": "metabolic", "icon": "Activity", "priority": 1,
        "conflict_group": "blood-sugar",
        "blurb": "Carefully timed carbs to coordinate with insulin doses.",
        "keywords": ["type 1 diabetes", "t1d", "insulin dependent", "juvenile diabetes"],
        "image": "https://images.unsplash.com/photo-1547592180-85f173990554?w=600",
        "foods_to_eat": ["consistent carb portions", "lean protein", "non-starchy vegetables", "healthy fats"],
        "foods_to_avoid": ["unpredictable high-GI foods", "alcohol without food", "large meals"],
        "food_rules": [
            "Count carbohydrates consistently — 45-60g per main meal.",
            "Never skip meals while on insulin; carry fast carbs for hypoglycaemia.",
            "Include protein in every meal to stabilise blood sugar.",
        ],
    },
    {
        "id": "prediabetes", "label": "Pre-Diabetes",
        "category": "metabolic", "icon": "Activity", "priority": 2,
        "conflict_group": "blood-sugar",
        "blurb": "Reverse insulin resistance with diet and lifestyle changes.",
        "keywords": ["prediabetes", "pre diabetes", "borderline diabetes", "insulin resistance", "high blood sugar"],
        "image": "https://images.unsplash.com/photo-1547592180-85f173990554?w=600",
        "foods_to_eat": ["whole grains", "vegetables", "legumes", "nuts", "seeds"],
        "foods_to_avoid": ["processed foods", "sugary snacks", "refined carbs"],
        "food_rules": [
            "Swap refined carbs for whole grain equivalents immediately.",
            "A 5-7% body weight reduction can reverse pre-diabetes.",
            "Walk 30 minutes daily — exercise is as powerful as medication here.",
        ],
    },
    {
        "id": "pcos", "label": "PCOS",
        "category": "metabolic", "icon": "Flower2", "priority": 2,
        "conflict_group": "hormonal",
        "blurb": "Insulin-friendly, anti-inflammatory foods to restore hormonal balance.",
        "keywords": ["pcos", "polycystic ovary", "pcod", "hormonal imbalance"],
        "image": "https://images.unsplash.com/photo-1517093602195-b40af9688b4e?w=600",
        "foods_to_eat": ["anti-inflammatory foods", "omega-3", "magnesium-rich foods", "fiber", "spearmint tea"],
        "foods_to_avoid": ["refined sugar", "processed foods", "high-GI foods", "dairy (some)"],
        "food_rules": [
            "Eat low-GI to manage insulin — the root driver of PCOS.",
            "Anti-inflammatory foods (turmeric, berries, olive oil) reduce androgen levels.",
            "Include omega-3 fatty acids from flaxseed, walnuts, and fatty fish.",
            "Limit dairy if it worsens acne or other symptoms.",
        ],
    },
    {
        "id": "thyroid", "label": "Thyroid (Hypothyroid)",
        "category": "metabolic", "icon": "Sparkles", "priority": 2,
        "conflict_group": "thyroid",
        "blurb": "Selenium and iodine-balanced foods, minimal raw goitrogens.",
        "keywords": ["thyroid", "hypothyroid", "underactive thyroid", "hashimoto"],
        "image": "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=600",
        "foods_to_eat": ["selenium-rich foods", "iodized salt", "fish", "eggs", "Brazil nuts"],
        "foods_to_avoid": ["raw cruciferous vegetables in excess", "soy in excess", "processed foods"],
        "food_rules": [
            "Cook cruciferous vegetables — this neutralises most goitrogens.",
            "Selenium from Brazil nuts (1-2/day) supports T4→T3 conversion.",
            "Take thyroid medication 30-60 min before breakfast, separate from soy or calcium.",
        ],
    },
    {
        "id": "hyperthyroid", "label": "Thyroid (Hyperthyroid)",
        "category": "metabolic", "icon": "Sparkles", "priority": 2,
        "conflict_group": "thyroid",
        "blurb": "Limit iodine-rich foods; support calorie needs during hypermetabolism.",
        "keywords": ["hyperthyroid", "overactive thyroid", "graves disease"],
        "image": "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=600",
        "foods_to_eat": ["calcium-rich foods", "vitamin D foods", "cruciferous vegetables", "anti-inflammatory foods"],
        "foods_to_avoid": ["iodine-rich foods", "seaweed", "iodized salt in excess", "caffeine", "alcohol"],
        "food_rules": [
            "Limit high-iodine foods: seaweed, excessive seafood, iodized salt.",
            "Increase calorie intake — hyperthyroid speeds up metabolism.",
            "Calcium and vitamin D protect against bone loss from elevated thyroid hormones.",
        ],
    },
    {
        "id": "insulin-resistance", "label": "Insulin Resistance",
        "category": "metabolic", "icon": "Activity", "priority": 2,
        "conflict_group": "blood-sugar",
        "blurb": "Targeted low-GI eating to restore insulin sensitivity.",
        "keywords": ["insulin resistance", "metabolic syndrome", "hyperinsulinemia"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["high-fiber foods", "lean protein", "healthy fats", "low-GI carbs", "magnesium foods"],
        "foods_to_avoid": ["added sugars", "refined carbs", "trans fats", "alcohol"],
        "food_rules": [
            "Every meal should include protein, fiber, and healthy fat — never carbs alone.",
            "Magnesium (spinach, almonds, pumpkin seeds) directly improves insulin sensitivity.",
            "Intermittent fasting may help — consult doctor before starting.",
        ],
    },

    # ── Cardiovascular ────────────────────────────────────────────────────────
    {
        "id": "heart-disease", "label": "Heart Disease",
        "category": "cardiovascular", "icon": "Heart", "priority": 1,
        "conflict_group": "cardiovascular",
        "blurb": "Omega-3 rich, low-sodium, low-saturated-fat meals.",
        "keywords": ["heart disease", "cardiovascular", "coronary", "heart attack", "CAD"],
        "image": "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600",
        "foods_to_eat": ["fatty fish", "oats", "walnuts", "olive oil", "berries", "dark leafy greens"],
        "foods_to_avoid": ["processed meats", "trans fats", "high-sodium foods", "full-fat dairy"],
        "food_rules": [
            "Sodium under 1500mg/day — read all labels carefully.",
            "Eat fatty fish (salmon, mackerel) twice a week for EPA/DHA.",
            "Replace saturated fats with unsaturated: olive oil, avocado, nuts.",
            "Oat beta-glucan actively lowers LDL cholesterol.",
        ],
    },
    {
        "id": "hypertension", "label": "High Blood Pressure",
        "category": "cardiovascular", "icon": "Gauge", "priority": 1,
        "conflict_group": "cardiovascular",
        "blurb": "DASH-aligned eating, sodium under 500mg per meal.",
        "keywords": ["hypertension", "high blood pressure", "BP", "blood pressure"],
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
        "foods_to_eat": ["potassium-rich foods", "leafy greens", "berries", "beets", "garlic", "dark chocolate"],
        "foods_to_avoid": ["salt", "processed foods", "canned soups", "pickles", "alcohol"],
        "food_rules": [
            "DASH diet: more vegetables, whole grains, lean protein — less salt.",
            "Potassium (banana, potato) counteracts sodium's BP-raising effect.",
            "Beet juice provides dietary nitrates that lower systolic BP by 4-5 mmHg.",
            "Limit alcohol to 1 drink/day max.",
        ],
    },
    {
        "id": "high-cholesterol", "label": "High Cholesterol",
        "category": "cardiovascular", "icon": "Heart", "priority": 2,
        "conflict_group": "cardiovascular",
        "blurb": "Soluble fiber and unsaturated fats to lower LDL levels.",
        "keywords": ["high cholesterol", "hyperlipidemia", "LDL", "cholesterol"],
        "image": "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600",
        "foods_to_eat": ["oats", "barley", "beans", "eggplant", "okra", "apples", "citrus", "nuts"],
        "foods_to_avoid": ["saturated fats", "trans fats", "full-fat dairy", "red meat", "fried foods"],
        "food_rules": [
            "Soluble fiber (oats, beans, psyllium) directly binds and removes LDL.",
            "Plant sterols (fortified foods, wheat germ) block cholesterol absorption.",
            "Replace butter with olive oil and nuts for healthy fat profile.",
        ],
    },
    {
        "id": "high-triglycerides", "label": "High Triglycerides",
        "category": "cardiovascular", "icon": "Gauge", "priority": 2,
        "conflict_group": "cardiovascular",
        "blurb": "Reduce refined carbs and sugars; increase omega-3 intake.",
        "keywords": ["triglycerides", "hypertriglyceridemia", "VLDL"],
        "image": "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600",
        "foods_to_eat": ["fatty fish", "avocado", "nuts", "leafy greens", "whole grains"],
        "foods_to_avoid": ["refined sugar", "alcohol", "white bread", "fruit juice", "sweets"],
        "food_rules": [
            "Cut added sugar completely — sugar is converted directly to triglycerides.",
            "Omega-3 fatty acids (fish oil, fatty fish) reduce triglycerides by 20-30%.",
            "Limit alcohol — even moderate amounts raise triglyceride levels significantly.",
        ],
    },

    # ── Digestive / GI ────────────────────────────────────────────────────────
    {
        "id": "gut-health", "label": "Gut Health",
        "category": "digestive", "icon": "Leaf", "priority": 3,
        "conflict_group": "digestive",
        "blurb": "Fermented foods and soluble fibre for microbiome diversity.",
        "keywords": ["gut health", "digestive health", "microbiome", "IBS", "bloating"],
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600",
        "foods_to_eat": ["curd", "kimchi", "kefir", "oats", "bananas", "garlic", "onions", "diverse plant foods"],
        "foods_to_avoid": ["artificial sweeteners", "processed foods", "excess alcohol", "high-fat fried foods"],
        "food_rules": [
            "Eat 30 different plant foods per week for microbiome diversity.",
            "Include fermented foods daily: curd, idli, dosa, kimchi, kefir.",
            "Prebiotic fiber (garlic, onions, bananas) feeds beneficial bacteria.",
        ],
    },
    {
        "id": "ibs", "label": "IBS",
        "category": "digestive", "icon": "Leaf", "priority": 2,
        "conflict_group": "digestive",
        "blurb": "Low-FODMAP diet to reduce bloating, cramping, and irregularity.",
        "keywords": ["IBS", "irritable bowel", "irritable bowel syndrome", "bloating", "cramping"],
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600",
        "foods_to_eat": ["rice", "oats", "carrots", "zucchini", "blueberries", "strawberries", "lactose-free dairy"],
        "foods_to_avoid": ["garlic", "onion", "wheat", "milk", "apples", "pears", "legumes in excess"],
        "food_rules": [
            "Follow low-FODMAP protocol for 6-8 weeks with dietician supervision.",
            "Reintroduce FODMAP foods one at a time to identify personal triggers.",
            "Soluble fiber (oats, psyllium) helps regulate both diarrhea and constipation.",
        ],
    },
    {
        "id": "gerd", "label": "Acid Reflux / GERD",
        "category": "digestive", "icon": "Leaf", "priority": 2,
        "conflict_group": "digestive",
        "blurb": "Avoid trigger foods; eat small, frequent, upright meals.",
        "keywords": ["GERD", "acid reflux", "heartburn", "acidity", "gastroesophageal"],
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600",
        "foods_to_eat": ["oatmeal", "ginger", "bananas", "melons", "fennel", "lean protein", "alkaline foods"],
        "foods_to_avoid": ["spicy food", "tomatoes", "citrus", "coffee", "alcohol", "chocolate", "mint", "fatty foods"],
        "food_rules": [
            "Eat smaller meals more frequently; never lie down within 2 hours of eating.",
            "Avoid trigger foods: spicy, citrus, tomatoes, coffee, chocolate, alcohol.",
            "Elevate the head of bed by 6-8 inches if nighttime reflux occurs.",
        ],
    },
    {
        "id": "fatty-liver", "label": "Fatty Liver (NAFLD)",
        "category": "digestive", "icon": "Leaf", "priority": 2,
        "conflict_group": "digestive",
        "blurb": "Reduce liver fat with low-sugar, high-fiber Mediterranean-style eating.",
        "keywords": ["fatty liver", "NAFLD", "NASH", "liver disease", "non-alcoholic"],
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600",
        "foods_to_eat": ["coffee", "omega-3 foods", "cruciferous vegetables", "walnuts", "olive oil", "avocado"],
        "foods_to_avoid": ["added sugar", "fructose", "alcohol", "refined carbs", "saturated fats"],
        "food_rules": [
            "Cut all added sugar — fructose specifically drives liver fat accumulation.",
            "Coffee (2-3 cups/day) is protective against liver inflammation — genuinely.",
            "Mediterranean-style eating (vegetables, olive oil, fish) reduces liver fat by 20-30%.",
        ],
    },
    {
        "id": "celiac", "label": "Coeliac Disease",
        "category": "digestive", "icon": "ShieldOff", "priority": 1,
        "conflict_group": "gluten",
        "blurb": "Strict gluten-free diet — even trace amounts cause damage.",
        "keywords": ["celiac", "coeliac", "gluten intolerance", "gluten free", "wheat allergy"],
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600",
        "foods_to_eat": ["rice", "quinoa", "buckwheat", "millet", "corn", "potatoes", "all fruits and vegetables"],
        "foods_to_avoid": ["wheat", "barley", "rye", "spelt", "kamut", "malt", "most soy sauce"],
        "food_rules": [
            "Zero tolerance for gluten — even 20ppm can trigger intestinal damage.",
            "Check all labels for wheat, barley, rye, malt, and hidden gluten sources.",
            "Use separate cookware and avoid cross-contamination in shared kitchens.",
        ],
    },
    {
        "id": "gastritis", "label": "Gastritis",
        "category": "digestive", "icon": "Leaf", "priority": 2,
        "conflict_group": "digestive",
        "blurb": "Soft, low-acid, non-irritating foods during flares and recovery.",
        "keywords": ["gastritis", "stomach inflammation", "H. pylori", "stomach ulcer"],
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600",
        "foods_to_eat": ["oatmeal", "bananas", "applesauce", "rice", "cooked vegetables", "yogurt", "ginger"],
        "foods_to_avoid": ["spicy food", "alcohol", "coffee", "acidic foods", "fried foods", "NSAIDs with food"],
        "food_rules": [
            "Eat small, frequent, non-irritating meals — never on an empty stomach for long.",
            "Avoid NSAIDs (aspirin, ibuprofen) — they worsen gastric lining damage.",
            "Manuka honey has documented anti-H. pylori properties.",
        ],
    },

    # ── Kidney / Liver ────────────────────────────────────────────────────────
    {
        "id": "kidney-disease", "label": "Kidney Disease (CKD)",
        "category": "kidney-liver", "icon": "Droplets", "priority": 1,
        "conflict_group": "kidney",
        "blurb": "Low potassium, low phosphorus, controlled protein to protect kidneys.",
        "keywords": ["kidney disease", "CKD", "chronic kidney", "renal failure", "nephropathy"],
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
        "foods_to_eat": ["egg whites", "cauliflower", "cabbage", "apples", "blueberries", "white rice", "olive oil"],
        "foods_to_avoid": ["bananas", "potatoes", "tomatoes", "dairy in excess", "nuts", "processed foods", "colas"],
        "food_rules": [
            "Limit potassium — boil vegetables and discard water to reduce potassium by 30-50%.",
            "Restrict phosphorus: avoid cola drinks, processed foods, and excessive dairy.",
            "Protein needs vary by CKD stage — consult nephrologist for exact targets.",
            "Sodium under 1500mg/day to control blood pressure and fluid retention.",
        ],
    },
    {
        "id": "kidney-stones", "label": "Kidney Stones",
        "category": "kidney-liver", "icon": "Droplets", "priority": 2,
        "conflict_group": "kidney",
        "blurb": "High hydration and diet changes based on stone type.",
        "keywords": ["kidney stones", "renal stones", "nephrolithiasis", "oxalate"],
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
        "foods_to_eat": ["water (3+ litres)", "citrus fruits", "calcium-rich foods (with meals)", "lemon juice"],
        "foods_to_avoid": ["spinach", "beets", "nuts", "chocolate (for oxalate stones)", "excessive salt", "animal protein in excess"],
        "food_rules": [
            "Drink at least 3 litres of water daily — urine should be pale yellow.",
            "Paradoxically, eat adequate calcium (with meals) — it binds oxalate in gut.",
            "Limit animal protein — it raises uric acid and reduces urinary citrate.",
        ],
    },

    # ── Nutritional Deficiencies ──────────────────────────────────────────────
    {
        "id": "iron-deficiency", "label": "Iron Deficiency Anaemia",
        "category": "deficiency", "icon": "Droplets", "priority": 2,
        "conflict_group": "deficiency",
        "blurb": "Iron-rich foods paired with vitamin C to maximize absorption.",
        "keywords": ["iron deficiency", "anaemia", "anemia", "low iron", "low hemoglobin", "fatigue"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["lentils", "spinach", "tofu", "pumpkin seeds", "fortified cereals", "dark chocolate", "red meat"],
        "foods_to_avoid": ["tea/coffee with meals", "calcium with iron supplements", "phytic acid-rich foods with iron"],
        "food_rules": [
            "Pair iron-rich foods with vitamin C (lemon, bell pepper) to triple absorption.",
            "Avoid tea and coffee within 1 hour of meals — tannins block iron absorption.",
            "Cook in cast iron — small but meaningful amount of iron leaches into food.",
        ],
    },
    {
        "id": "b12-deficiency", "label": "Vitamin B12 Deficiency",
        "category": "deficiency", "icon": "Sparkles", "priority": 2,
        "conflict_group": "deficiency",
        "blurb": "B12-rich animal foods or fortified alternatives; supplement if vegan.",
        "keywords": ["B12", "vitamin B12", "cobalamin", "b12 deficiency", "pernicious anaemia"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["eggs", "dairy", "fish", "meat", "fortified plant milk", "nutritional yeast"],
        "foods_to_avoid": ["nothing specific — deficiency is about what to ADD"],
        "food_rules": [
            "B12 is found almost exclusively in animal foods — vegans must supplement.",
            "Fortified plant milks and nutritional yeast are reliable vegan B12 sources.",
            "Absorption decreases with age — people over 50 should supplement regardless of diet.",
        ],
    },
    {
        "id": "vitamin-d", "label": "Vitamin D Deficiency",
        "category": "deficiency", "icon": "Sun", "priority": 2,
        "conflict_group": "deficiency",
        "blurb": "Sunlight + D3 supplement + D-rich foods for bone and immune health.",
        "keywords": ["vitamin D", "vit D", "vitamin D deficiency", "bone health", "rickets"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["fatty fish", "egg yolks", "fortified milk", "mushrooms (UV-exposed)", "cod liver oil"],
        "foods_to_avoid": ["nothing specific — supplementation is usually required"],
        "food_rules": [
            "Food alone is insufficient — most deficient individuals need D3 supplements.",
            "20-30 minutes of midday sunlight daily on skin produces 1000-2000 IU vitamin D.",
            "Take vitamin D with the largest fat-containing meal for best absorption.",
        ],
    },
    {
        "id": "calcium-deficiency", "label": "Calcium Deficiency",
        "category": "deficiency", "icon": "Bone", "priority": 2,
        "conflict_group": "deficiency",
        "blurb": "Calcium-rich foods with vitamin D for bone density and muscle function.",
        "keywords": ["calcium deficiency", "low calcium", "osteopenia", "bone health"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["dairy", "fortified plant milk", "sesame seeds", "ragi", "kale", "sardines", "tofu"],
        "foods_to_avoid": ["excessive salt", "excessive caffeine", "excessive alcohol (all reduce calcium retention)"],
        "food_rules": [
            "Adults need 1000-1200mg calcium daily — split into 2-3 doses for better absorption.",
            "Pair calcium with vitamin D — without D3, absorption is minimal.",
            "Ragi (finger millet) is one of the richest plant sources of calcium.",
        ],
    },

    # ── Allergies / Intolerances ──────────────────────────────────────────────
    {
        "id": "gluten-intolerance", "label": "Gluten Intolerance",
        "category": "allergy", "icon": "ShieldOff", "priority": 2,
        "conflict_group": "gluten",
        "blurb": "Avoid wheat, barley, rye — switch to naturally gluten-free grains.",
        "keywords": ["gluten", "gluten intolerance", "gluten sensitivity", "wheat allergy"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["rice", "quinoa", "millet", "oats (certified GF)", "buckwheat", "corn", "potatoes"],
        "foods_to_avoid": ["wheat", "barley", "rye", "spelt", "most breads and pasta"],
        "food_rules": [
            "Read labels carefully — gluten hides in soy sauce, soups, and sauces.",
            "Oats are naturally gluten-free but often contaminated — buy certified gluten-free.",
        ],
    },
    {
        "id": "lactose-intolerance", "label": "Lactose Intolerance",
        "category": "allergy", "icon": "ShieldOff", "priority": 2,
        "conflict_group": None,
        "blurb": "Limit lactose; choose lactose-free or plant-based dairy alternatives.",
        "keywords": ["lactose", "lactose intolerance", "dairy intolerance", "milk allergy"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["lactose-free milk", "hard cheeses", "yogurt (often tolerated)", "plant milk", "ragi for calcium"],
        "foods_to_avoid": ["milk", "soft cheese", "ice cream", "cream", "butter in excess"],
        "food_rules": [
            "Hard cheeses (cheddar, parmesan) are very low in lactose and usually well-tolerated.",
            "Yogurt's live cultures partially digest lactose — most people tolerate it.",
            "Lactase enzyme supplements allow dairy consumption without symptoms.",
        ],
    },

    # ── Hormonal / Reproductive ───────────────────────────────────────────────
    {
        "id": "menopause", "label": "Menopause",
        "category": "hormonal", "icon": "Flower2", "priority": 3,
        "conflict_group": "hormonal",
        "blurb": "Phytoestrogens, calcium, and cooling foods to ease menopause symptoms.",
        "keywords": ["menopause", "perimenopause", "hot flashes", "postmenopause"],
        "image": "https://images.unsplash.com/photo-1517093602195-b40af9688b4e?w=600",
        "foods_to_eat": ["soy (phytoestrogens)", "flaxseed", "calcium-rich foods", "omega-3", "whole grains"],
        "foods_to_avoid": ["spicy food (triggers hot flashes)", "alcohol", "caffeine", "refined sugar"],
        "food_rules": [
            "Phytoestrogens (soy, flaxseed) may reduce hot flash frequency by 20-30%.",
            "Prioritise calcium and vitamin D — bone loss accelerates significantly after menopause.",
            "Limit alcohol and caffeine — both worsen hot flashes and disrupt sleep.",
        ],
    },
    {
        "id": "pregnancy", "label": "Pregnancy",
        "category": "hormonal", "icon": "Heart", "priority": 1,
        "conflict_group": "hormonal",
        "blurb": "Folate, iron, DHA, and iodine for healthy fetal development.",
        "keywords": ["pregnancy", "prenatal", "expecting", "maternal nutrition"],
        "image": "https://images.unsplash.com/photo-1517093602195-b40af9688b4e?w=600",
        "foods_to_eat": ["folate-rich foods", "iron-rich foods", "DHA (fatty fish)", "dairy", "lean protein", "colorful vegetables"],
        "foods_to_avoid": ["raw fish", "unpasteurized cheese", "raw eggs", "alcohol", "high-mercury fish", "excess liver/vitamin A"],
        "food_rules": [
            "Folate (400-600mcg) is critical in first trimester to prevent neural tube defects.",
            "DHA from oily fish (2 servings/week, low mercury) supports baby brain development.",
            "Avoid raw/undercooked foods — listeria and salmonella are serious risks in pregnancy.",
            "Iron needs nearly double in pregnancy — include iron-rich foods at every meal.",
        ],
    },

    # ── Autoimmune ────────────────────────────────────────────────────────────
    {
        "id": "hashimotos", "label": "Hashimoto's Thyroiditis",
        "category": "autoimmune", "icon": "Shield", "priority": 2,
        "conflict_group": "thyroid",
        "blurb": "Anti-inflammatory, selenium-rich diet; consider gluten-free trial.",
        "keywords": ["hashimoto", "hashimotos", "autoimmune thyroid", "thyroiditis"],
        "image": "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=600",
        "foods_to_eat": ["selenium-rich foods", "anti-inflammatory foods", "omega-3", "zinc foods", "probiotic foods"],
        "foods_to_avoid": ["gluten (try elimination)", "soy in excess", "processed foods", "iodine in excess"],
        "food_rules": [
            "Trial gluten-free diet for 3-6 months — some Hashimoto's patients show significant antibody reduction.",
            "Selenium (Brazil nuts, eggs, turkey) reduces thyroid antibody levels.",
            "Avoid excess iodine (seaweed supplements) — it can trigger flares.",
        ],
    },
    {
        "id": "rheumatoid-arthritis", "label": "Rheumatoid Arthritis",
        "category": "autoimmune", "icon": "Shield", "priority": 2,
        "conflict_group": "autoimmune",
        "blurb": "Anti-inflammatory Mediterranean diet to reduce joint pain and swelling.",
        "keywords": ["rheumatoid arthritis", "RA", "arthritis", "joint pain", "autoimmune"],
        "image": "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=600",
        "foods_to_eat": ["fatty fish", "olive oil", "berries", "turmeric", "ginger", "walnuts", "tart cherry"],
        "foods_to_avoid": ["processed foods", "refined sugar", "red meat in excess", "alcohol", "trans fats"],
        "food_rules": [
            "Mediterranean diet adherence is associated with lower RA disease activity.",
            "Tart cherry juice reduces gout-related uric acid and may help RA inflammation.",
            "Omega-3 supplements (fish oil) reduce joint stiffness and tenderness.",
        ],
    },

    # ── Mental / Neurological ─────────────────────────────────────────────────
    {
        "id": "depression", "label": "Depression / Low Mood",
        "category": "mental", "icon": "Brain", "priority": 3,
        "conflict_group": "mental",
        "blurb": "Mood-supporting nutrients: omega-3, B vitamins, magnesium, and gut health.",
        "keywords": ["depression", "low mood", "mental health", "mood disorder"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["fatty fish", "dark chocolate", "fermented foods", "leafy greens", "walnuts", "berries", "whole grains"],
        "foods_to_avoid": ["alcohol", "processed foods", "refined sugar", "ultra-processed snacks"],
        "food_rules": [
            "Omega-3 (EPA specifically) is among the most evidence-backed dietary interventions for depression.",
            "Gut-brain axis: fermented foods and fiber improve mood via microbiome pathways.",
            "Magnesium deficiency is strongly associated with depression — include nuts, seeds, leafy greens.",
        ],
    },
    {
        "id": "migraine", "label": "Migraines",
        "category": "mental", "icon": "Brain", "priority": 2,
        "conflict_group": "mental",
        "blurb": "Identify and avoid personal food triggers; maintain regular eating schedule.",
        "keywords": ["migraine", "headache", "cluster headache"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["magnesium-rich foods", "riboflavin (B2) foods", "ginger tea", "regular hydration"],
        "foods_to_avoid": ["common triggers: red wine, aged cheese, chocolate, MSG, processed meats with nitrates, caffeine withdrawal"],
        "food_rules": [
            "Keep a food diary for 6 weeks to identify your personal migraine triggers.",
            "Never skip meals — blood sugar drops are a reliable migraine trigger.",
            "Magnesium (400mg) and riboflavin (400mg) are evidence-backed preventive supplements.",
        ],
    },

    # ── Other ─────────────────────────────────────────────────────────────────
    {
        "id": "gout", "label": "Gout",
        "category": "other", "icon": "Droplets", "priority": 2,
        "conflict_group": "uric-acid",
        "blurb": "Low-purine diet and high hydration to prevent uric acid crystal formation.",
        "keywords": ["gout", "uric acid", "gout attack", "hyperuricemia"],
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
        "foods_to_eat": ["cherries", "tart cherry juice", "water", "vitamin C foods", "low-fat dairy", "coffee"],
        "foods_to_avoid": ["organ meats", "shellfish", "red meat in excess", "alcohol (especially beer)", "high-fructose corn syrup", "anchovies", "sardines"],
        "food_rules": [
            "Tart cherry consumption (10-12 cherries daily) reduces gout attacks by 35%.",
            "Drink 8-10 glasses of water daily to flush uric acid through kidneys.",
            "Alcohol — especially beer — dramatically increases uric acid production.",
            "Low-fat dairy is protective: it promotes uric acid excretion.",
        ],
    },
    {
        "id": "osteoporosis", "label": "Osteoporosis",
        "category": "other", "icon": "Bone", "priority": 2,
        "conflict_group": "bone",
        "blurb": "Calcium, vitamin D, and protein to maintain bone density.",
        "keywords": ["osteoporosis", "osteopenia", "bone density", "brittle bones"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["dairy", "ragi", "kale", "sardines", "tofu", "fortified foods", "eggs"],
        "foods_to_avoid": ["excessive alcohol", "excessive caffeine", "excessive salt", "smoking"],
        "food_rules": [
            "1200mg calcium daily (split doses) + 800-1000 IU vitamin D3.",
            "Adequate protein (1g/kg body weight) is essential for bone matrix maintenance.",
            "Weight-bearing exercise is non-negotiable alongside dietary changes.",
        ],
    },
    {
        "id": "obesity", "label": "Obesity",
        "category": "other", "icon": "Scale", "priority": 2,
        "conflict_group": None,
        "blurb": "Calorie-controlled, high-protein, high-fiber approach for sustainable loss.",
        "keywords": ["obesity", "overweight", "weight loss", "BMI"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["lean protein", "vegetables", "legumes", "whole grains", "water before meals"],
        "foods_to_avoid": ["ultra-processed foods", "liquid calories", "refined carbs", "large portions"],
        "food_rules": [
            "500 kcal/day deficit produces ~0.5kg/week loss sustainably.",
            "Protein at 1.2-1.6g/kg preserves muscle during caloric restriction.",
            "Volume eating (vegetables, broth-based soups) reduces hunger within calorie limits.",
        ],
    },
    # Legacy entries kept for backward compatibility with seed data
    {
        "id": "weight-management", "label": "Weight Management",
        "category": "other", "icon": "Scale", "priority": 3,
        "conflict_group": None,
        "blurb": "High-protein, satiating, calorie-aware eating for steady progress.",
        "keywords": ["weight management", "maintain weight", "healthy weight"],
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "foods_to_eat": ["lean protein", "high-fiber vegetables", "whole grains", "healthy fats"],
        "foods_to_avoid": ["processed snacks", "liquid calories", "refined sugar"],
        "food_rules": [
            "Protein at every meal increases satiety and preserves lean muscle.",
            "Eat slowly — satiety signals take 20 minutes to reach the brain.",
            "Track portions for 2 weeks to calibrate your sense of correct serving sizes.",
        ],
    },
    {
        "id": "immunity", "label": "Immunity & Wellness",
        "category": "other", "icon": "Shield", "priority": 3,
        "conflict_group": None,
        "blurb": "Vitamin C, zinc, and antioxidant-rich foods for immune resilience.",
        "keywords": ["immunity", "immune health", "wellness", "antioxidants", "frequent illness"],
        "image": "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600",
        "foods_to_eat": ["citrus", "amla", "turmeric", "garlic", "ginger", "yogurt", "bell pepper", "spinach"],
        "foods_to_avoid": ["excess sugar (suppresses immune function for hours)", "alcohol", "ultra-processed foods"],
        "food_rules": [
            "Vitamin C from amla (gooseberry) is 20x more concentrated than orange.",
            "Zinc (pumpkin seeds, legumes) is essential for immune cell development.",
            "Sleep 7-9 hours — it's the most powerful immune-supporting behaviour you have.",
        ],
    },
]

# Conditions shown as the default "Common" section in onboarding (first 8, backward compatible)
COMMON_CONDITIONS = [c for c in CONDITIONS if c["id"] in {
    "heart-disease", "diabetes", "thyroid", "pcos",
    "weight-management", "hypertension", "gut-health", "immunity",
}]

# Per-recipe enrichments — keyed by existing seed_data recipe id
ENRICHMENTS = {
    "hc-001": {
        "meal_type": "lunch", "prep_minutes": 30,
        "health_scores": ["diabetes-safe", "heart-friendly", "anti-inflammatory"],
        "nutritional_tags": ["low-sodium", "low-GI", "high-fibre", "anti-inflammatory"],
        "why_this_works": {
            "diabetes": "Low GI (32) and 12g fibre keep blood sugar stable for hours.",
            "heart-disease": "No saturated fat, turmeric is anti-inflammatory, sodium under 200mg.",
            "hypertension": "Sodium 180mg — well within DASH guidelines.",
        },
    },
    "hc-002": {
        "meal_type": "dinner", "prep_minutes": 25,
        "health_scores": ["heart-friendly", "thyroid-supportive", "post-surgery-safe"],
        "nutritional_tags": ["omega-3", "high-protein", "low-sodium", "gluten-free"],
        "why_this_works": {
            "heart-disease": "Rich in omega-3 (EPA/DHA) — reduces triglycerides; sodium just 95mg.",
            "thyroid": "Selenium from salmon supports T4→T3 conversion.",
            "post-surgery": "34g lean protein speeds tissue repair; easy to digest.",
        },
    },
    "hc-003": {
        "meal_type": "lunch", "prep_minutes": 20,
        "health_scores": ["kidney-friendly", "heart-friendly"],
        "nutritional_tags": ["low-potassium", "low-sodium", "plant-based", "gluten-free"],
        "why_this_works": {
            "kidney-disease": "Avoids high-potassium veg (no spinach/tomato); sodium under 30mg.",
            "hypertension": "Plant-based, fibre-rich; supports BP control.",
            "weight-management": "290 kcal, 9g protein, 6g fibre — satiating without spike.",
        },
    },
    "hc-004": {
        "meal_type": "breakfast", "prep_minutes": 5,
        "health_scores": ["diabetes-safe", "pcos-friendly"],
        "nutritional_tags": ["high-fibre", "low-GI", "plant-based", "anti-inflammatory"],
        "why_this_works": {
            "pcos": "13g fibre + chia omega-3 reduce insulin resistance markers.",
            "diabetes": "GI 40 — overnight soak lowers carbs' impact on glucose curve.",
            "weight-management": "Slow-release carbs; cinnamon helps glucose disposal.",
        },
    },
    "hc-005": {
        "meal_type": "dinner", "prep_minutes": 35,
        "health_scores": ["gentle-on-gut", "post-surgery-safe"],
        "nutritional_tags": ["soft-texture", "easy-digest", "vegetarian"],
        "why_this_works": {
            "elderly-nutrition": "Soft, mashable, complete protein from rice + dal combo.",
            "post-surgery": "Low fibre when needed, high digestibility, gentle spicing.",
            "gut-health": "Bland, easy-on-stomach for IBS or GERD flares.",
        },
    },
}

# Additional healthcare recipes covering breakfast/lunch/dinner/snacks across conditions
def _ing(name, amount, q=None):
    qstr = (q or name).split(",")[0].strip().replace(" ", "+")
    return {"name": name, "amount": amount,
            "image": f"https://source.unsplash.com/120x120/?{qstr},food,ingredient"}


EXTRA_RECIPES = [
    {
        "id": "hc-006", "title": "Beetroot & Apple Detox Smoothie",
        "category": "healthcare",
        "conditions": ["heart-disease", "hypertension", "immunity", "weight-management"],
        "country": "International", "region": "Wellness",
        "image": "https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800",
        "video_url": "https://www.youtube.com/embed/8YFYeGfX8jE",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 5, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "drink"],
        "description": "Nitrate-rich beet smoothie that gently lowers blood pressure.",
        "ingredients": [
            _ing("Cooked beetroot", "120g", "beetroot"),
            _ing("Green apple", "1 medium", "apple"),
            _ing("Fresh ginger", "1 tsp", "ginger"),
            _ing("Lemon juice", "1 tbsp", "lemon"),
            _ing("Cold water", "200ml", "water"),
        ],
        "steps": [
            "Blend everything until smooth.",
            "Strain if you prefer a thin texture.",
            "Serve immediately for best nutrient retention.",
        ],
        "nutrition": {"calories": 130, "protein": 2, "carbs": 30, "fat": 0, "fiber": 6, "sodium": 90, "gi": 38},
        "_enrichment": {
            "meal_type": "snack", "prep_minutes": 5,
            "health_scores": ["heart-friendly", "diabetes-safe", "immunity-boost"],
            "nutritional_tags": ["nitrate-rich", "low-sodium", "antioxidant", "low-calorie"],
            "why_this_works": {
                "hypertension": "Dietary nitrates from beets convert to NO, lowering systolic BP by ~4-5 mmHg.",
                "heart-disease": "Polyphenols + zero saturated fat support endothelial health.",
                "immunity": "Vit C from apple + lemon, plus betalains, support immune cells.",
            },
        },
    },
    {
        "id": "hc-007", "title": "Greek Yogurt with Walnuts & Honey",
        "category": "healthcare",
        "conditions": ["gut-health", "thyroid", "weight-management", "pcos"],
        "country": "Greece", "region": "Mediterranean",
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800",
        "video_url": "https://www.youtube.com/embed/3F9LkEX5xqQ",
        "cuisine": "Greek", "difficulty": "Easy", "cook_time": 3, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian", "high-protein", "snack"],
        "description": "Probiotic-rich Greek yogurt with omega-3 walnuts.",
        "ingredients": [
            _ing("Greek yogurt (full-fat)", "200g", "greek+yogurt"),
            _ing("Walnuts, chopped", "20g", "walnut"),
            _ing("Raw honey", "1 tsp", "honey"),
            _ing("Cinnamon", "1/4 tsp", "cinnamon"),
        ],
        "steps": [
            "Spoon yogurt into a bowl.",
            "Top with walnuts, honey, and a pinch of cinnamon.",
        ],
        "nutrition": {"calories": 280, "protein": 18, "carbs": 14, "fat": 16, "fiber": 2, "sodium": 70, "gi": 35},
        "_enrichment": {
            "meal_type": "snack", "prep_minutes": 3,
            "health_scores": ["gut-friendly", "pcos-friendly"],
            "nutritional_tags": ["probiotic", "high-protein", "omega-3"],
            "why_this_works": {
                "gut-health": "Live cultures (L. acidophilus, Bifidobacterium) support microbiome diversity.",
                "thyroid": "Selenium from walnuts + tyrosine from yogurt aid thyroid hormone production.",
                "pcos": "High protein + healthy fat keeps insulin steady; cinnamon further sensitises.",
            },
        },
    },
    {
        "id": "hc-008", "title": "Spinach & Egg Scramble",
        "category": "healthcare",
        "conditions": ["weight-management", "heart-disease", "immunity", "thyroid"],
        "country": "International", "region": "International",
        "image": "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800",
        "video_url": "https://www.youtube.com/embed/PUP7U5vTMM0",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 8, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian", "high-protein", "gluten-free"],
        "description": "12-minute breakfast: complete protein + leafy greens.",
        "ingredients": [
            _ing("Eggs", "2 large", "egg"),
            _ing("Baby spinach", "60g", "spinach"),
            _ing("Olive oil", "1 tsp", "olive+oil"),
            _ing("Garlic, minced", "1 clove", "garlic"),
            _ing("Black pepper", "1/4 tsp", "pepper"),
        ],
        "steps": [
            "Heat 1 tsp olive oil in non-stick pan.",
            "Saute garlic 20 sec, add spinach, wilt 1 min.",
            "Whisk eggs with pepper, pour over spinach.",
            "Stir gently until curds form, 2 min. Serve.",
        ],
        "nutrition": {"calories": 220, "protein": 16, "carbs": 4, "fat": 15, "fiber": 2, "sodium": 160, "gi": 0},
        "_enrichment": {
            "meal_type": "breakfast", "prep_minutes": 8,
            "health_scores": ["heart-friendly", "thyroid-supportive", "immunity-boost"],
            "nutritional_tags": ["high-protein", "iron-rich", "low-carb", "vit-A"],
            "why_this_works": {
                "weight-management": "16g protein keeps you full till lunch; only 220 kcal.",
                "thyroid": "Iodine + selenium from eggs support thyroid hormone synthesis.",
                "immunity": "Vit A + folate from spinach, complete protein from eggs.",
            },
        },
    },
    {
        "id": "hc-009", "title": "Roasted Chickpea Crunch",
        "category": "healthcare",
        "conditions": ["weight-management", "diabetes", "gut-health", "pcos"],
        "country": "Mediterranean", "region": "Mediterranean",
        "image": "https://images.unsplash.com/photo-1559054663-e8d23213f55c?w=800",
        "video_url": "https://www.youtube.com/embed/sPHbEJTVlIM",
        "cuisine": "Mediterranean", "difficulty": "Easy", "cook_time": 30, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "snack", "high-protein"],
        "description": "Crunchy savoury snack — replaces chips, doubles as salad topper.",
        "ingredients": [
            _ing("Cooked chickpeas, drained", "400g", "chickpeas"),
            _ing("Olive oil", "1 tbsp", "olive+oil"),
            _ing("Smoked paprika", "1 tsp", "paprika"),
            _ing("Cumin powder", "1/2 tsp", "cumin"),
            _ing("Garlic powder", "1/2 tsp", "garlic"),
            _ing("Sea salt", "1/4 tsp", "salt"),
        ],
        "steps": [
            "Preheat oven to 200°C.",
            "Pat chickpeas very dry. Toss with oil + spices.",
            "Spread on tray, roast 25-30 min, shaking halfway.",
            "Cool 5 min for max crunch.",
        ],
        "nutrition": {"calories": 180, "protein": 9, "carbs": 22, "fat": 6, "fiber": 7, "sodium": 240, "gi": 28},
        "_enrichment": {
            "meal_type": "snack", "prep_minutes": 30,
            "health_scores": ["diabetes-safe", "gut-friendly", "pcos-friendly"],
            "nutritional_tags": ["high-fibre", "low-GI", "plant-protein"],
            "why_this_works": {
                "diabetes": "GI 28 — slow-release carbs; 7g fibre slows glucose absorption.",
                "gut-health": "Resistant starch + fibre feed beneficial gut bacteria.",
                "weight-management": "180 kcal · 9g protein · 7g fibre — guilt-free crunch.",
            },
        },
    },
    {
        "id": "hc-010", "title": "Lemon Ginger Wellness Tea",
        "category": "healthcare",
        "conditions": ["immunity", "gut-health", "thyroid"],
        "country": "International", "region": "Wellness",
        "image": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800",
        "video_url": "https://www.youtube.com/embed/IBgJ-XnX-9c",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 5, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "drink"],
        "description": "5-minute zero-calorie immunity drink.",
        "ingredients": [
            _ing("Fresh ginger", "10g sliced", "ginger"),
            _ing("Lemon", "1/2", "lemon"),
            _ing("Raw honey", "1 tsp", "honey"),
            _ing("Hot water", "300ml", "water"),
        ],
        "steps": [
            "Steep ginger in hot water 4 min.",
            "Add lemon juice and honey; stir.",
        ],
        "nutrition": {"calories": 30, "protein": 0, "carbs": 8, "fat": 0, "fiber": 0, "sodium": 5, "gi": 0},
        "_enrichment": {
            "meal_type": "snack", "prep_minutes": 5,
            "health_scores": ["immunity-boost", "gut-friendly"],
            "nutritional_tags": ["antioxidant", "low-calorie", "anti-inflammatory"],
            "why_this_works": {
                "immunity": "Gingerols + Vit C from lemon support white blood cell function.",
                "gut-health": "Soothes nausea, supports digestive enzymes.",
                "thyroid": "Caffeine-free, won't interfere with thyroid medication.",
            },
        },
    },
    {
        "id": "hc-011", "title": "Quinoa Tabbouleh with Mint",
        "category": "healthcare",
        "conditions": ["weight-management", "heart-disease", "diabetes", "gut-health"],
        "country": "Lebanon", "region": "Mediterranean",
        "image": "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800",
        "video_url": "https://www.youtube.com/embed/7xHxQ9XLn2g",
        "cuisine": "Lebanese", "difficulty": "Easy", "cook_time": 15, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "high-protein"],
        "description": "Cold-prep lunch in 15 minutes — fresh, filling, plant-forward.",
        "ingredients": [
            _ing("Cooked quinoa", "200g", "quinoa"),
            _ing("Cucumber, diced", "1/2", "cucumber"),
            _ing("Cherry tomatoes, halved", "150g", "tomato"),
            _ing("Fresh parsley, chopped", "30g", "parsley"),
            _ing("Fresh mint", "10g", "mint"),
            _ing("Lemon juice", "2 tbsp", "lemon"),
            _ing("Olive oil", "1 tbsp", "olive+oil"),
        ],
        "steps": [
            "Combine quinoa, cucumber, tomatoes, parsley, mint.",
            "Whisk lemon juice with olive oil; toss with salad.",
            "Chill 10 min for flavours to meld.",
        ],
        "nutrition": {"calories": 260, "protein": 8, "carbs": 36, "fat": 9, "fiber": 6, "sodium": 60, "gi": 45},
        "_enrichment": {
            "meal_type": "lunch", "prep_minutes": 15,
            "health_scores": ["heart-friendly", "diabetes-safe", "gut-friendly"],
            "nutritional_tags": ["high-fibre", "plant-protein", "low-sodium"],
            "why_this_works": {
                "weight-management": "Filling 260 kcal lunch with 6g fibre and 8g protein.",
                "heart-disease": "Quinoa lignans + olive oil support cholesterol balance.",
                "diabetes": "Quinoa GI 45, cucumber zero — smooth glucose curve.",
            },
        },
    },
    {
        "id": "hc-012", "title": "Sweet Potato & Black Bean Bowl",
        "category": "healthcare",
        "conditions": ["heart-disease", "diabetes", "gut-health", "weight-management"],
        "country": "USA", "region": "International",
        "image": "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800",
        "video_url": "https://www.youtube.com/embed/TSVw6MrlR-w",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 35, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "high-protein"],
        "description": "Plant-protein dinner that supports heart, gut, and steady energy.",
        "ingredients": [
            _ing("Sweet potato, cubed", "300g", "sweet+potato"),
            _ing("Black beans, cooked", "240g", "black+beans"),
            _ing("Avocado", "1/2", "avocado"),
            _ing("Lime juice", "1 tbsp", "lime"),
            _ing("Cumin powder", "1 tsp", "cumin"),
            _ing("Olive oil", "1 tbsp", "olive+oil"),
            _ing("Fresh cilantro", "10g", "cilantro"),
        ],
        "steps": [
            "Roast sweet potato with olive oil + cumin at 200°C for 25 min.",
            "Warm black beans.",
            "Plate sweet potato, beans, sliced avocado.",
            "Drizzle lime, top with cilantro.",
        ],
        "nutrition": {"calories": 410, "protein": 14, "carbs": 56, "fat": 14, "fiber": 14, "sodium": 220, "gi": 50},
        "_enrichment": {
            "meal_type": "dinner", "prep_minutes": 35,
            "health_scores": ["heart-friendly", "diabetes-safe", "gut-friendly"],
            "nutritional_tags": ["high-fibre", "potassium-rich", "plant-protein"],
            "why_this_works": {
                "heart-disease": "Soluble fibre from beans lowers LDL; avocado adds heart-healthy fat.",
                "diabetes": "Resistant starch + 14g fibre = controlled glucose response.",
                "gut-health": "Prebiotic fibre feeds gut microbiome; supports short-chain fatty acid production.",
            },
        },
    },
]


# Smart ingredient swaps — surfaced inside Healthcare hub
SWAPS = [
    {"from": "Sugar", "to": "Dates / Maple syrup", "reason": "Lower GI, adds fibre & minerals.", "best_for": ["diabetes", "pcos"]},
    {"from": "Cream", "to": "Greek yogurt", "reason": "1/3 the saturated fat, double the protein.", "best_for": ["heart-disease", "weight-management"]},
    {"from": "Frying", "to": "Air-fry / Bake", "reason": "Cuts oil by 70-80% with similar crisp.", "best_for": ["heart-disease", "weight-management", "hypertension"]},
    {"from": "Salt", "to": "Lemon + herbs", "reason": "Brightens flavour without sodium.", "best_for": ["hypertension", "kidney-disease"]},
    {"from": "White rice", "to": "Quinoa / Brown rice", "reason": "Lower GI, more fibre & protein.", "best_for": ["diabetes", "pcos"]},
    {"from": "Butter", "to": "Olive oil / Avocado", "reason": "Monounsaturated fats over saturated.", "best_for": ["heart-disease"]},
    {"from": "Soda", "to": "Sparkling water + lemon", "reason": "Zero sugar, same fizz.", "best_for": ["diabetes", "weight-management"]},
    {"from": "Wheat flour", "to": "Almond / Chickpea flour", "reason": "Higher protein, lower GI.", "best_for": ["diabetes", "pcos"]},
]
