"""Seed recipe data for Zenplato — global, healthcare, fitness, chef-specials.
Each recipe has: ingredients with per-item image, cooking video URL, region tags.
"""

# Helper to build ingredient with image (Unsplash photo query)
def ing(name, amount, q=None):
    qstr = (q or name).split(",")[0].strip().replace(" ", "+")
    return {
        "name": name,
        "amount": amount,
        "image": f"https://source.unsplash.com/120x120/?{qstr},food,ingredient",
    }


RECIPES = [
    # ============ HEALTHCARE (5) ============
    {
        "id": "hc-001", "title": "Turmeric Ginger Lentil Dal",
        "category": "healthcare",
        "conditions": ["diabetes", "heart-disease", "hypertension"],
        "country": "India", "region": "North India",
        "image": "https://images.unsplash.com/photo-1604152135912-04a022e23696?w=800",
        "video_url": "https://www.youtube.com/embed/Z2HdEgTV_3o",
        "cuisine": "Indian", "difficulty": "Easy", "cook_time": 30, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian", "vegan", "gluten-free"],
        "description": "Anti-inflammatory dal safe for diabetics. Low GI, high fiber.",
        "ingredients": [
            ing("Red lentils (masoor dal)", "200g", "lentils"),
            ing("Turmeric powder", "1 tsp", "turmeric"),
            ing("Fresh ginger, grated", "1 tbsp", "ginger"),
            ing("Cumin seeds", "1 tsp", "cumin"),
            ing("Olive oil", "1 tbsp", "olive+oil"),
            ing("Tomato, diced", "1 medium (150g)", "tomato"),
            ing("Water", "750ml", "water"),
            ing("Salt (low sodium)", "1/2 tsp", "salt"),
        ],
        "steps": [
            "Rinse 200g red lentils until water runs clear.",
            "Heat 1 tbsp olive oil; add 1 tsp cumin and 1 tbsp grated ginger.",
            "Add diced tomato and 1 tsp turmeric. Cook 3 min.",
            "Add lentils and 750ml water. Simmer 20 minutes.",
            "Season with 1/2 tsp low-sodium salt. Serve warm.",
        ],
        "nutrition": {"calories": 245, "protein": 16, "carbs": 38, "fat": 4, "fiber": 12, "sodium": 180, "gi": 32},
        "avoid": ["white rice", "refined sugar", "deep fried papad"],
    },
    {
        "id": "hc-002", "title": "Baked Salmon with Steamed Broccoli",
        "category": "healthcare", "conditions": ["heart-disease", "post-surgery", "thyroid"],
        "country": "USA", "region": "Pacific Northwest",
        "image": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800",
        "video_url": "https://www.youtube.com/embed/9rRTQwZ_OOQ",
        "cuisine": "American", "difficulty": "Easy", "cook_time": 25, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["pescatarian", "gluten-free", "dairy-free"],
        "description": "Omega-3 rich salmon for heart health and post-surgery recovery.",
        "ingredients": [
            ing("Salmon fillet", "300g", "salmon"),
            ing("Broccoli florets", "300g", "broccoli"),
            ing("Olive oil", "2 tsp", "olive+oil"),
            ing("Lemon juice", "2 tbsp", "lemon"),
            ing("Garlic, minced", "2 cloves", "garlic"),
            ing("Black pepper", "1/2 tsp", "pepper"),
        ],
        "steps": [
            "Preheat oven to 200°C / 400°F.",
            "Rub salmon with 1 tsp olive oil, lemon juice, garlic, black pepper.",
            "Bake 12-15 minutes until flaky.",
            "Steam broccoli 5 minutes until tender-crisp.",
            "Drizzle with 1 tsp olive oil and serve.",
        ],
        "nutrition": {"calories": 380, "protein": 34, "carbs": 12, "fat": 22, "fiber": 5, "sodium": 95, "gi": 15},
        "avoid": ["fried fish", "heavy cream sauces"],
    },
    {
        "id": "hc-003", "title": "Quinoa Veggie Bowl for Kidney Health",
        "category": "healthcare", "conditions": ["kidney-disease", "hypertension", "obesity"],
        "country": "Peru", "region": "Andean",
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
        "video_url": "https://www.youtube.com/embed/dyhbzLrfTRk",
        "cuisine": "Peruvian", "difficulty": "Easy", "cook_time": 20, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free"],
        "description": "Low-potassium, kidney-friendly bowl with balanced protein.",
        "ingredients": [
            ing("Quinoa", "120g", "quinoa"),
            ing("Cucumber, diced", "1 medium (150g)", "cucumber"),
            ing("Bell pepper, diced", "1 medium (120g)", "bell+pepper"),
            ing("Olive oil", "1 tbsp", "olive+oil"),
            ing("Fresh cilantro", "2 tbsp chopped", "cilantro"),
            ing("Lemon juice", "1 tbsp", "lemon"),
        ],
        "steps": [
            "Rinse 120g quinoa, cook in 240ml water for 15 min.",
            "Dice cucumber and bell pepper.",
            "Toss cooked quinoa with vegetables.",
            "Dress with 1 tbsp olive oil, lemon juice, cilantro.",
            "Serve chilled or at room temperature.",
        ],
        "nutrition": {"calories": 290, "protein": 9, "carbs": 48, "fat": 8, "fiber": 6, "sodium": 25, "gi": 53},
        "avoid": ["tomato", "spinach", "high-sodium dressings"],
    },
    {
        "id": "hc-004", "title": "PCOS-Friendly Chia Overnight Oats",
        "category": "healthcare", "conditions": ["pcos", "diabetes", "obesity"],
        "country": "USA", "region": "International",
        "image": "https://images.unsplash.com/photo-1517093602195-b40af9688b4e?w=800",
        "video_url": "https://www.youtube.com/embed/8OSReg1fHxQ",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 5, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian", "gluten-free"],
        "description": "High-fiber, low-GI breakfast to balance insulin for PCOS.",
        "ingredients": [
            ing("Rolled oats", "50g", "oats"),
            ing("Chia seeds", "15g", "chia+seeds"),
            ing("Unsweetened almond milk", "200ml", "almond+milk"),
            ing("Cinnamon powder", "1/2 tsp", "cinnamon"),
            ing("Mixed berries", "80g", "berries"),
            ing("Walnuts, chopped", "15g", "walnuts"),
        ],
        "steps": [
            "Combine oats, chia, almond milk, cinnamon in a jar.",
            "Stir well; refrigerate overnight (min 6 hours).",
            "Top with berries and walnuts before serving.",
        ],
        "nutrition": {"calories": 355, "protein": 12, "carbs": 42, "fat": 16, "fiber": 13, "sodium": 120, "gi": 40},
        "avoid": ["sugar-sweetened yogurt"],
    },
    {
        "id": "hc-005", "title": "Elderly Soft Vegetable Khichdi",
        "category": "healthcare", "conditions": ["elderly-nutrition", "post-surgery"],
        "country": "India", "region": "North India",
        "image": "https://images.unsplash.com/photo-1626203049284-c7f1f8b4f2a2?w=800",
        "video_url": "https://www.youtube.com/embed/_O0DWiQ69Vw",
        "cuisine": "Indian", "difficulty": "Easy", "cook_time": 35, "servings": 3,
        "is_premium": True, "tier": "premium",
        "tags": ["vegetarian", "gluten-free"],
        "description": "Soft, easily digestible, nutrient-dense one-pot meal.",
        "ingredients": [
            ing("Basmati rice", "100g", "basmati+rice"),
            ing("Moong dal", "100g", "moong+dal"),
            ing("Carrot, diced", "1 medium", "carrot"),
            ing("Zucchini, diced", "1 small", "zucchini"),
            ing("Ghee", "1 tbsp", "ghee"),
            ing("Cumin seeds", "1 tsp", "cumin"),
            ing("Turmeric", "1/2 tsp", "turmeric"),
            ing("Water", "900ml", "water"),
        ],
        "steps": [
            "Rinse rice and dal together.",
            "Heat 1 tbsp ghee, add 1 tsp cumin seeds.",
            "Add diced vegetables and 1/2 tsp turmeric. Saute 3 min.",
            "Add rice, dal, 900ml water. Simmer 25-30 min until soft.",
            "Mash slightly for porridge-like texture.",
        ],
        "nutrition": {"calories": 310, "protein": 14, "carbs": 52, "fat": 6, "fiber": 7, "sodium": 95, "gi": 58},
        "avoid": ["spicy food", "tough meats"],
    },

    # ============ FITNESS (5) ============
    {
        "id": "ft-001", "title": "Grilled Chicken & Sweet Potato Power Bowl",
        "category": "fitness", "goals": ["muscle-gain", "cutting", "maintain"],
        "country": "USA", "region": "International",
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
        "video_url": "https://www.youtube.com/embed/B5b2cN3rIS0",
        "cuisine": "American", "difficulty": "Easy", "cook_time": 25, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["gluten-free", "dairy-free", "high-protein"],
        "description": "Post-workout power bowl with clean macros.",
        "ingredients": [
            ing("Chicken breast", "200g", "chicken+breast"),
            ing("Sweet potato", "250g", "sweet+potato"),
            ing("Mixed greens", "80g", "salad+greens"),
            ing("Avocado", "1/2 (70g)", "avocado"),
            ing("Olive oil", "1 tbsp", "olive+oil"),
            ing("Paprika", "1 tsp", "paprika"),
            ing("Garlic powder", "1/2 tsp", "garlic"),
        ],
        "steps": [
            "Season chicken with paprika, garlic powder, salt.",
            "Grill chicken 6 min per side until 75°C internal.",
            "Roast cubed sweet potato at 220°C for 20 min.",
            "Slice chicken, plate with greens, sweet potato, avocado.",
            "Drizzle 1 tbsp olive oil and serve.",
        ],
        "nutrition": {"calories": 520, "protein": 48, "carbs": 52, "fat": 14, "fiber": 9, "sodium": 210, "gi": 63},
        "meal_timing": "Post-workout",
    },
    {
        "id": "ft-002", "title": "Greek Yogurt Protein Parfait",
        "category": "fitness", "goals": ["muscle-gain", "maintain"],
        "country": "Greece", "region": "Mediterranean",
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800",
        "video_url": "https://www.youtube.com/embed/3F9LkEX5xqQ",
        "cuisine": "Greek", "difficulty": "Easy", "cook_time": 5, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian", "gluten-free", "high-protein"],
        "description": "Quick pre-workout breakfast with fast protein.",
        "ingredients": [
            ing("Greek yogurt (non-fat)", "250g", "greek+yogurt"),
            ing("Honey", "1 tsp", "honey"),
            ing("Granola", "30g", "granola"),
            ing("Mixed berries", "100g", "berries"),
            ing("Almonds, sliced", "15g", "almonds"),
        ],
        "steps": ["Layer yogurt, granola, berries in a glass.", "Drizzle 1 tsp honey.", "Top with sliced almonds."],
        "nutrition": {"calories": 380, "protein": 28, "carbs": 48, "fat": 9, "fiber": 6, "sodium": 110, "gi": 42},
        "meal_timing": "Pre-workout / Breakfast",
    },
    {
        "id": "ft-003", "title": "Lean Beef Stir-Fry with Brown Rice",
        "category": "fitness", "goals": ["bulking", "muscle-gain"],
        "country": "China", "region": "Cantonese",
        "image": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800",
        "video_url": "https://www.youtube.com/embed/aPfpT6q9Qno",
        "cuisine": "Chinese", "difficulty": "Medium", "cook_time": 25, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["dairy-free", "high-protein"],
        "description": "Classic bulking meal: lean protein + slow carbs.",
        "ingredients": [
            ing("Lean beef sirloin, sliced", "300g", "beef"),
            ing("Brown rice (cooked)", "300g", "brown+rice"),
            ing("Broccoli florets", "200g", "broccoli"),
            ing("Bell pepper, sliced", "1 medium", "bell+pepper"),
            ing("Low-sodium soy sauce", "2 tbsp", "soy+sauce"),
            ing("Sesame oil", "1 tbsp", "sesame+oil"),
            ing("Garlic, minced", "2 cloves", "garlic"),
            ing("Ginger, grated", "1 tsp", "ginger"),
        ],
        "steps": [
            "Heat wok with 1 tbsp sesame oil on high.",
            "Stir-fry beef 2-3 min, remove.",
            "Add garlic, ginger, vegetables. Stir-fry 4 min.",
            "Return beef, add 2 tbsp soy sauce. Toss 1 min.",
            "Serve over 150g brown rice per portion.",
        ],
        "nutrition": {"calories": 610, "protein": 42, "carbs": 68, "fat": 18, "fiber": 7, "sodium": 480, "gi": 55},
        "meal_timing": "Lunch / Post-workout",
    },
    {
        "id": "ft-004", "title": "Tuna Avocado Toast",
        "category": "fitness", "goals": ["cutting", "maintain"],
        "country": "Italy", "region": "Coastal",
        "image": "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800",
        "video_url": "https://www.youtube.com/embed/M4lTNDqDMzQ",
        "cuisine": "Italian", "difficulty": "Easy", "cook_time": 7, "servings": 1,
        "is_premium": False, "tier": "budget",
        "tags": ["pescatarian", "high-protein"],
        "description": "Fast cutting-phase meal, high protein, moderate fats.",
        "ingredients": [
            ing("Whole grain bread", "2 slices (80g)", "bread"),
            ing("Canned tuna (water)", "150g", "tuna"),
            ing("Avocado", "1/2 (70g)", "avocado"),
            ing("Lemon juice", "1 tsp", "lemon"),
            ing("Red chili flakes", "1/4 tsp", "chili"),
            ing("Black pepper", "1/4 tsp", "pepper"),
        ],
        "steps": [
            "Toast bread slices.",
            "Mash avocado with lemon juice and pepper.",
            "Spread on toast.",
            "Top with drained tuna and chili flakes.",
        ],
        "nutrition": {"calories": 420, "protein": 38, "carbs": 34, "fat": 14, "fiber": 9, "sodium": 460, "gi": 50},
        "meal_timing": "Lunch",
    },
    {
        "id": "ft-005", "title": "Endurance Oatmeal Energy Bowl",
        "category": "fitness", "goals": ["endurance", "bulking"],
        "country": "USA", "region": "International",
        "image": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800",
        "video_url": "https://www.youtube.com/embed/_pCOWFq0aFY",
        "cuisine": "International", "difficulty": "Easy", "cook_time": 10, "servings": 1,
        "is_premium": True, "tier": "premium",
        "tags": ["vegetarian", "high-carb"],
        "description": "Slow-release carbs for long endurance sessions.",
        "ingredients": [
            ing("Rolled oats", "80g", "oats"),
            ing("Banana, sliced", "1 medium", "banana"),
            ing("Peanut butter", "1 tbsp", "peanut+butter"),
            ing("Whole milk", "250ml", "milk"),
            ing("Honey", "1 tsp", "honey"),
            ing("Chia seeds", "1 tbsp", "chia+seeds"),
        ],
        "steps": [
            "Cook 80g oats in 250ml milk 5 minutes.",
            "Stir in 1 tbsp peanut butter and 1 tsp honey.",
            "Top with banana and chia seeds.",
        ],
        "nutrition": {"calories": 580, "protein": 22, "carbs": 84, "fat": 16, "fiber": 11, "sodium": 150, "gi": 58},
        "meal_timing": "Pre-workout (90 min before)",
    },

    # ============ CULTURAL — INDIAN REGIONAL ============
    {
        "id": "in-south-001", "title": "Idli Sambar",
        "category": "cultural", "country": "India", "region": "South India",
        "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800",
        "video_url": "https://www.youtube.com/embed/_KCkbi0NgL0",
        "cuisine": "South Indian", "difficulty": "Medium", "cook_time": 30, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian", "vegan", "gluten-free"],
        "description": "Steamed rice cakes served with a tangy lentil-vegetable stew — a South Indian breakfast classic.",
        "ingredients": [
            ing("Idli batter (fermented rice + urad dal)", "500g", "idli+batter"),
            ing("Toor dal", "150g", "toor+dal"),
            ing("Tamarind pulp", "2 tbsp", "tamarind"),
            ing("Sambar powder", "2 tbsp", "spice+powder"),
            ing("Drumstick, chopped", "1 small", "drumstick+vegetable"),
            ing("Tomato", "1 medium", "tomato"),
            ing("Mustard seeds", "1 tsp", "mustard+seeds"),
            ing("Curry leaves", "10 leaves", "curry+leaves"),
            ing("Asafoetida", "1/4 tsp", "spice"),
        ],
        "steps": [
            "Steam idli batter in greased molds 10–12 min.",
            "Pressure-cook toor dal with turmeric until soft.",
            "Simmer dal with tamarind, sambar powder, vegetables.",
            "Temper with mustard seeds, curry leaves, asafoetida in oil.",
            "Pour tempering on sambar; serve with idlis.",
        ],
        "nutrition": {"calories": 320, "protein": 14, "carbs": 56, "fat": 5, "fiber": 8, "sodium": 480, "gi": 55},
    },
    {
        "id": "in-south-002", "title": "Masala Dosa",
        "category": "cultural", "country": "India", "region": "South India",
        "image": "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800",
        "video_url": "https://www.youtube.com/embed/PiJgWQ1xr1Y",
        "cuisine": "South Indian", "difficulty": "Medium", "cook_time": 25, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian"],
        "description": "Crispy fermented crêpe filled with spiced potato — Karnataka & Tamil Nadu staple.",
        "ingredients": [
            ing("Dosa batter", "400g", "dosa+batter"),
            ing("Potatoes, boiled", "300g", "potato"),
            ing("Onion, sliced", "1 medium", "onion"),
            ing("Green chilies", "2", "green+chili"),
            ing("Mustard seeds", "1 tsp", "mustard+seeds"),
            ing("Turmeric", "1/2 tsp", "turmeric"),
            ing("Curry leaves", "8", "curry+leaves"),
            ing("Oil", "2 tbsp", "oil"),
        ],
        "steps": [
            "Saute mustard seeds, curry leaves, chilies, onion in 1 tbsp oil.",
            "Add turmeric and mashed potato. Cook 4 min.",
            "Heat skillet, ladle dosa batter and spread thin.",
            "Drizzle oil, cook until crispy.",
            "Place potato filling, fold dosa, serve hot.",
        ],
        "nutrition": {"calories": 410, "protein": 9, "carbs": 72, "fat": 10, "fiber": 5, "sodium": 320, "gi": 65},
    },
    {
        "id": "in-north-001", "title": "Butter Chicken (Murgh Makhani)",
        "category": "cultural", "country": "India", "region": "North India",
        "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800",
        "video_url": "https://www.youtube.com/embed/a03U45jFxOI",
        "cuisine": "North Indian", "difficulty": "Medium", "cook_time": 50, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["gluten-free"],
        "description": "Delhi's iconic creamy tomato chicken curry.",
        "ingredients": [
            ing("Chicken thigh, cubed", "600g", "chicken"),
            ing("Greek yogurt", "150g", "yogurt"),
            ing("Garam masala", "2 tsp", "garam+masala"),
            ing("Tomato puree", "400g", "tomato+puree"),
            ing("Heavy cream", "100ml", "cream"),
            ing("Ginger-garlic paste", "2 tbsp", "ginger+garlic"),
            ing("Butter", "3 tbsp", "butter"),
            ing("Kasuri methi", "1 tsp", "kasuri+methi"),
        ],
        "steps": [
            "Marinate chicken in yogurt, 1 tsp garam masala, ginger-garlic 30 min.",
            "Grill or broil chicken until charred.",
            "Saute remaining ginger-garlic in butter.",
            "Add tomato puree, simmer 10 min.",
            "Add cream, garam masala, kasuri methi, chicken. Simmer 5 min.",
        ],
        "nutrition": {"calories": 460, "protein": 40, "carbs": 14, "fat": 26, "fiber": 3, "sodium": 520, "gi": 25},
    },
    {
        "id": "in-east-001", "title": "Bengali Macher Jhol",
        "category": "cultural", "country": "India", "region": "East India",
        "image": "https://images.unsplash.com/photo-1633237308525-cd587cf71926?w=800",
        "video_url": "https://www.youtube.com/embed/DTQGzpMgHjw",
        "cuisine": "Bengali", "difficulty": "Medium", "cook_time": 35, "servings": 3,
        "is_premium": False, "tier": "budget",
        "tags": ["pescatarian", "gluten-free", "dairy-free"],
        "description": "Light Bengali fish curry with potatoes — soulful homestyle.",
        "ingredients": [
            ing("Rohu fish, cut", "500g", "fish"),
            ing("Potato, cubed", "2 medium", "potato"),
            ing("Mustard oil", "3 tbsp", "mustard+oil"),
            ing("Nigella seeds", "1/2 tsp", "nigella"),
            ing("Turmeric", "1 tsp", "turmeric"),
            ing("Green chilies, slit", "3", "green+chili"),
            ing("Tomato, chopped", "1 medium", "tomato"),
        ],
        "steps": [
            "Rub fish with turmeric and salt; pan-fry 2 min/side. Remove.",
            "Heat mustard oil, temper nigella seeds.",
            "Add potatoes, fry 4 min. Add tomato, chilies, 1/2 tsp turmeric.",
            "Add 500ml water, simmer 12 min.",
            "Slip fish in; simmer 5 min. Garnish with cilantro.",
        ],
        "nutrition": {"calories": 340, "protein": 30, "carbs": 18, "fat": 16, "fiber": 3, "sodium": 380, "gi": 50},
    },
    {
        "id": "in-west-001", "title": "Mumbai Pav Bhaji",
        "category": "cultural", "country": "India", "region": "West India",
        "image": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800",
        "video_url": "https://www.youtube.com/embed/Lkl_thJrTI8",
        "cuisine": "Maharashtrian", "difficulty": "Easy", "cook_time": 30, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian"],
        "description": "Iconic Mumbai street food — buttery vegetable mash with toasted pav.",
        "ingredients": [
            ing("Mixed vegetables (potato, peas, cauliflower)", "500g", "vegetables"),
            ing("Tomato, chopped", "300g", "tomato"),
            ing("Onion, chopped", "2 medium", "onion"),
            ing("Pav buns", "8", "bread+rolls"),
            ing("Pav bhaji masala", "2 tbsp", "spice+powder"),
            ing("Butter", "4 tbsp", "butter"),
            ing("Lemon", "1", "lemon"),
        ],
        "steps": [
            "Boil and mash mixed vegetables.",
            "Saute onions and tomato in butter 6 min.",
            "Add pav bhaji masala and mash. Cook 4 min.",
            "Add veggies, simmer 8 min, mashing.",
            "Toast pav with butter; serve with bhaji and lemon.",
        ],
        "nutrition": {"calories": 470, "protein": 11, "carbs": 60, "fat": 22, "fiber": 7, "sodium": 760, "gi": 70},
    },

    # ============ CULTURAL — GLOBAL ============
    {
        "id": "cu-001", "title": "Margherita Pizza",
        "category": "cultural", "country": "Italy", "region": "Naples",
        "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
        "video_url": "https://www.youtube.com/embed/sv3TXMSv6Lw",
        "cuisine": "Italian", "difficulty": "Medium", "cook_time": 35, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian"],
        "description": "Iconic Neapolitan pizza — fresh basil, mozzarella, San Marzano tomatoes.",
        "ingredients": [
            ing("Pizza dough", "300g", "pizza+dough"),
            ing("San Marzano tomatoes", "150g", "tomato"),
            ing("Fresh mozzarella", "150g", "mozzarella"),
            ing("Fresh basil leaves", "10 leaves", "basil"),
            ing("Olive oil", "1 tbsp", "olive+oil"),
        ],
        "steps": [
            "Preheat oven to 250°C.",
            "Stretch dough; spread tomatoes and mozzarella.",
            "Bake 8-10 min until charred.",
            "Top with basil and olive oil.",
        ],
        "nutrition": {"calories": 560, "protein": 24, "carbs": 72, "fat": 18, "fiber": 4, "sodium": 680, "gi": 70},
    },
    {
        "id": "cu-002", "title": "Pad Thai with Shrimp",
        "category": "cultural", "country": "Thailand", "region": "Bangkok Street",
        "image": "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800",
        "video_url": "https://www.youtube.com/embed/5q0PXxMnHzs",
        "cuisine": "Thai", "difficulty": "Medium", "cook_time": 25, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["pescatarian", "dairy-free"],
        "description": "Thailand's famous street food — sweet, sour, savory noodles.",
        "ingredients": [
            ing("Rice noodles", "200g", "rice+noodles"),
            ing("Shrimp, peeled", "200g", "shrimp"),
            ing("Bean sprouts", "100g", "bean+sprouts"),
            ing("Eggs", "2", "egg"),
            ing("Tamarind paste", "2 tbsp", "tamarind"),
            ing("Fish sauce", "1.5 tbsp", "fish+sauce"),
            ing("Palm sugar", "1 tbsp", "sugar"),
            ing("Peanuts, crushed", "30g", "peanut"),
            ing("Lime wedges", "2", "lime"),
        ],
        "steps": [
            "Soak noodles 20 min.",
            "Whisk tamarind, fish sauce, sugar.",
            "Stir-fry shrimp 2 min, push aside, scramble eggs.",
            "Add noodles and sauce. Toss 2 min.",
            "Add bean sprouts; top with peanuts and lime.",
        ],
        "nutrition": {"calories": 490, "protein": 30, "carbs": 62, "fat": 14, "fiber": 4, "sodium": 1100, "gi": 68},
    },
    {
        "id": "cu-003", "title": "Chicken Teriyaki Donburi",
        "category": "cultural", "country": "Japan", "region": "Tokyo",
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
        "video_url": "https://www.youtube.com/embed/IP9Sx0nyA50",
        "cuisine": "Japanese", "difficulty": "Easy", "cook_time": 20, "servings": 2,
        "is_premium": False, "tier": "budget",
        "tags": ["dairy-free"],
        "description": "Glossy sweet-savory chicken over steamed rice.",
        "ingredients": [
            ing("Chicken thigh", "400g", "chicken"),
            ing("Japanese rice", "200g", "rice"),
            ing("Soy sauce", "3 tbsp", "soy+sauce"),
            ing("Mirin", "2 tbsp", "mirin"),
            ing("Sake", "1 tbsp", "sake"),
            ing("Sugar", "1 tbsp", "sugar"),
            ing("Scallions", "2", "scallion"),
            ing("Sesame seeds", "1 tsp", "sesame"),
        ],
        "steps": [
            "Steam rice.",
            "Sear chicken 6 min; flip, 4 min.",
            "Add soy, mirin, sake, sugar. Reduce to glaze.",
            "Slice chicken over rice with scallions and sesame.",
        ],
        "nutrition": {"calories": 590, "protein": 36, "carbs": 70, "fat": 18, "fiber": 2, "sodium": 980, "gi": 73},
    },
    {
        "id": "cu-004", "title": "Tacos al Pastor",
        "category": "cultural", "country": "Mexico", "region": "Mexico City",
        "image": "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=800",
        "video_url": "https://www.youtube.com/embed/0YYS2OaRAGI",
        "cuisine": "Mexican", "difficulty": "Medium", "cook_time": 45, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["dairy-free"],
        "description": "Pineapple-marinated pork tacos, Mexico City style.",
        "ingredients": [
            ing("Pork shoulder", "600g", "pork"),
            ing("Pineapple chunks", "200g", "pineapple"),
            ing("Achiote paste", "2 tbsp", "achiote"),
            ing("Orange juice", "100ml", "orange"),
            ing("Corn tortillas", "12", "tortilla"),
            ing("White onion", "1 small", "onion"),
            ing("Cilantro", "1/2 cup", "cilantro"),
            ing("Lime wedges", "4", "lime"),
        ],
        "steps": [
            "Blend achiote, OJ, half pineapple.",
            "Marinate pork 30 min.",
            "Grill pork 3 min/side; char remaining pineapple.",
            "Warm tortillas; assemble pork, pineapple, onion, cilantro, lime.",
        ],
        "nutrition": {"calories": 520, "protein": 34, "carbs": 48, "fat": 20, "fiber": 5, "sodium": 420, "gi": 52},
    },
    {
        "id": "cu-005", "title": "Korean Bibimbap",
        "category": "cultural", "country": "Korea", "region": "Seoul",
        "image": "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800",
        "video_url": "https://www.youtube.com/embed/Zi7ZnRSZ8yQ",
        "cuisine": "Korean", "difficulty": "Medium", "cook_time": 40, "servings": 2,
        "is_premium": True, "tier": "premium",
        "tags": ["dairy-free"],
        "description": "Colorful rice bowl with seasoned vegetables, beef, and a fried egg.",
        "ingredients": [
            ing("Short-grain rice", "200g", "rice"),
            ing("Beef sirloin, minced", "200g", "beef"),
            ing("Spinach", "100g", "spinach"),
            ing("Carrot, julienned", "1", "carrot"),
            ing("Bean sprouts", "100g", "bean+sprouts"),
            ing("Eggs", "2", "egg"),
            ing("Gochujang", "2 tbsp", "gochujang"),
            ing("Sesame oil", "2 tbsp", "sesame+oil"),
            ing("Soy sauce", "2 tbsp", "soy+sauce"),
        ],
        "steps": [
            "Cook rice.",
            "Marinate and saute beef 5 min.",
            "Blanch spinach and bean sprouts; dress separately with sesame oil.",
            "Saute carrot 2 min.",
            "Fry eggs sunny-side up.",
            "Arrange in bowl with gochujang.",
        ],
        "nutrition": {"calories": 640, "protein": 34, "carbs": 78, "fat": 20, "fiber": 6, "sodium": 890, "gi": 70},
    },
    {
        "id": "cu-006", "title": "Moroccan Chickpea Tagine",
        "category": "cultural", "country": "Morocco", "region": "Marrakesh",
        "image": "https://images.unsplash.com/photo-1574484184081-afea8a62f9ab?w=800",
        "video_url": "https://www.youtube.com/embed/Xx7PCKj-Ras",
        "cuisine": "Moroccan", "difficulty": "Easy", "cook_time": 40, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free"],
        "description": "Warmly spiced North African stew with chickpeas and apricots.",
        "ingredients": [
            ing("Chickpeas (cooked)", "400g", "chickpeas"),
            ing("Onion", "1 large", "onion"),
            ing("Canned tomatoes", "400g", "tomato"),
            ing("Dried apricots", "80g", "apricot"),
            ing("Ras el hanout", "2 tsp", "spice"),
            ing("Cumin", "1 tsp", "cumin"),
            ing("Olive oil", "2 tbsp", "olive+oil"),
            ing("Parsley", "1/4 cup", "parsley"),
        ],
        "steps": [
            "Saute onion in olive oil 5 min.",
            "Toast spices 1 min.",
            "Add tomatoes, chickpeas, apricots, 200ml water.",
            "Simmer 25 min until thick.",
            "Garnish with parsley.",
        ],
        "nutrition": {"calories": 340, "protein": 13, "carbs": 54, "fat": 9, "fiber": 12, "sodium": 380, "gi": 40},
    },
    {
        "id": "cu-007", "title": "Spanish Paella Valenciana",
        "category": "cultural", "country": "Spain", "region": "Valencia",
        "image": "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800",
        "video_url": "https://www.youtube.com/embed/QlpPGl0r2WM",
        "cuisine": "Spanish", "difficulty": "Hard", "cook_time": 60, "servings": 4,
        "is_premium": True, "tier": "premium",
        "tags": ["pescatarian"],
        "description": "Saffron-infused rice with seafood and chicken — Valencia's pride.",
        "ingredients": [
            ing("Bomba rice", "300g", "rice"),
            ing("Chicken thigh", "300g", "chicken"),
            ing("Shrimp", "200g", "shrimp"),
            ing("Mussels", "200g", "mussels"),
            ing("Saffron threads", "1/2 tsp", "saffron"),
            ing("Tomato puree", "100g", "tomato"),
            ing("Smoked paprika", "1 tsp", "paprika"),
            ing("Chicken stock", "900ml", "broth"),
            ing("Olive oil", "3 tbsp", "olive+oil"),
        ],
        "steps": [
            "Heat oil in paella pan; brown chicken 5 min.",
            "Add tomato, paprika, saffron-infused stock.",
            "Add rice in even layer; simmer without stirring 18 min.",
            "Add shrimp and mussels in last 8 min.",
            "Rest 5 min before serving.",
        ],
        "nutrition": {"calories": 620, "protein": 38, "carbs": 70, "fat": 18, "fiber": 3, "sodium": 720, "gi": 65},
    },
    {
        "id": "cu-008", "title": "Vietnamese Pho Bo",
        "category": "cultural", "country": "Vietnam", "region": "Hanoi",
        "image": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
        "video_url": "https://www.youtube.com/embed/qZkj1Dyc6gY",
        "cuisine": "Vietnamese", "difficulty": "Hard", "cook_time": 180, "servings": 4,
        "is_premium": True, "tier": "premium",
        "tags": ["dairy-free"],
        "description": "Aromatic beef noodle soup — Vietnam's national dish.",
        "ingredients": [
            ing("Beef bones", "1kg", "beef+bones"),
            ing("Beef brisket", "500g", "beef"),
            ing("Rice noodles (flat)", "300g", "rice+noodles"),
            ing("Star anise", "3", "star+anise"),
            ing("Cinnamon stick", "1", "cinnamon"),
            ing("Ginger", "50g", "ginger"),
            ing("Onion", "1 large", "onion"),
            ing("Fish sauce", "3 tbsp", "fish+sauce"),
            ing("Fresh herbs", "1 cup", "herbs"),
            ing("Lime wedges", "4", "lime"),
        ],
        "steps": [
            "Blanch bones 10 min, drain.",
            "Simmer bones, brisket, charred ginger and onion 2.5 hours.",
            "Toast spices, add to broth last 30 min.",
            "Strain broth; season with fish sauce.",
            "Soak noodles, place in bowl with brisket.",
            "Ladle broth, garnish with herbs and lime.",
        ],
        "nutrition": {"calories": 440, "protein": 34, "carbs": 58, "fat": 8, "fiber": 3, "sodium": 1300, "gi": 65},
    },
    {
        "id": "cu-009", "title": "French Ratatouille",
        "category": "cultural", "country": "France", "region": "Provence",
        "image": "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800",
        "video_url": "https://www.youtube.com/embed/uIcvtxAZeqM",
        "cuisine": "French", "difficulty": "Medium", "cook_time": 50, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free"],
        "description": "Slow-cooked Provençal vegetable stew with herbs de Provence.",
        "ingredients": [
            ing("Eggplant", "1 medium", "eggplant"),
            ing("Zucchini", "2", "zucchini"),
            ing("Bell pepper", "2", "bell+pepper"),
            ing("Tomatoes", "500g", "tomato"),
            ing("Onion", "1 large", "onion"),
            ing("Garlic", "4 cloves", "garlic"),
            ing("Olive oil", "4 tbsp", "olive+oil"),
            ing("Herbs de Provence", "1 tbsp", "herbs"),
        ],
        "steps": [
            "Slice all vegetables.",
            "Saute onion and garlic in olive oil.",
            "Layer vegetables in baking dish.",
            "Sprinkle herbs, drizzle olive oil.",
            "Bake at 180°C for 35 min.",
        ],
        "nutrition": {"calories": 230, "protein": 5, "carbs": 26, "fat": 13, "fiber": 8, "sodium": 90, "gi": 40},
    },
    {
        "id": "cu-010", "title": "Lebanese Falafel Wrap",
        "category": "cultural", "country": "Lebanon", "region": "Beirut",
        "image": "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=800",
        "video_url": "https://www.youtube.com/embed/5qmGFXG3HPo",
        "cuisine": "Lebanese", "difficulty": "Medium", "cook_time": 35, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan"],
        "description": "Crispy chickpea fritters wrapped in pita with tahini.",
        "ingredients": [
            ing("Dried chickpeas (soaked)", "300g", "chickpeas"),
            ing("Onion", "1 small", "onion"),
            ing("Garlic", "3 cloves", "garlic"),
            ing("Parsley", "1/2 cup", "parsley"),
            ing("Cumin", "1 tsp", "cumin"),
            ing("Coriander", "1 tsp", "coriander"),
            ing("Pita bread", "4", "pita"),
            ing("Tahini sauce", "4 tbsp", "tahini"),
            ing("Tomato, sliced", "1", "tomato"),
        ],
        "steps": [
            "Blend soaked chickpeas with onion, garlic, parsley, spices.",
            "Form into balls; rest 15 min.",
            "Deep-fry at 170°C for 4 min until golden.",
            "Stuff into pita with tahini, tomato, parsley.",
        ],
        "nutrition": {"calories": 480, "protein": 18, "carbs": 62, "fat": 18, "fiber": 12, "sodium": 520, "gi": 55},
    },

    # ============ CHEF SPECIALS — Desserts & Bakery ============
    {
        "id": "cs-001", "title": "Classic Tiramisu",
        "category": "chef-special", "country": "Italy", "region": "Veneto",
        "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
        "video_url": "https://www.youtube.com/embed/87CrLi0pQXc",
        "cuisine": "Italian Dessert", "difficulty": "Medium", "cook_time": 30, "servings": 6,
        "is_premium": True, "tier": "premium",
        "tags": ["vegetarian", "dessert"],
        "description": "Chef Lorenzo's signature mascarpone tiramisu — layered, espresso-soaked indulgence.",
        "chef": {"name": "Chef Lorenzo Bianchi", "credentials": "Michelin-starred, Milan"},
        "ingredients": [
            ing("Ladyfinger biscuits", "200g", "ladyfingers"),
            ing("Mascarpone cheese", "500g", "mascarpone"),
            ing("Eggs, separated", "4", "egg"),
            ing("Sugar", "100g", "sugar"),
            ing("Strong espresso", "300ml", "espresso"),
            ing("Cocoa powder", "2 tbsp", "cocoa"),
            ing("Marsala wine", "2 tbsp", "wine"),
        ],
        "steps": [
            "Whisk yolks with sugar until pale.",
            "Fold in mascarpone and Marsala.",
            "Whip egg whites to stiff peaks; fold in.",
            "Dip ladyfingers in espresso; layer in dish.",
            "Top with mascarpone cream; repeat.",
            "Refrigerate 6 hours; dust cocoa before serving.",
        ],
        "nutrition": {"calories": 480, "protein": 9, "carbs": 38, "fat": 32, "fiber": 1, "sodium": 90, "gi": 60},
    },
    {
        "id": "cs-002", "title": "French Macarons (Pistachio)",
        "category": "chef-special", "country": "France", "region": "Paris",
        "image": "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=800",
        "video_url": "https://www.youtube.com/embed/lcyCuQ8h3NM",
        "cuisine": "French Patisserie", "difficulty": "Hard", "cook_time": 90, "servings": 24,
        "is_premium": True, "tier": "premium",
        "tags": ["vegetarian", "dessert", "gluten-free"],
        "description": "Delicate almond-meringue shells with silky pistachio buttercream.",
        "chef": {"name": "Chef Amélie Dubois", "credentials": "Le Cordon Bleu, Paris"},
        "ingredients": [
            ing("Almond flour", "150g", "almond+flour"),
            ing("Powdered sugar", "150g", "powdered+sugar"),
            ing("Egg whites, aged", "100g", "egg+white"),
            ing("Caster sugar", "150g", "sugar"),
            ing("Pistachio paste", "60g", "pistachio"),
            ing("Butter, softened", "120g", "butter"),
            ing("Cream", "30ml", "cream"),
        ],
        "steps": [
            "Sift almond flour and powdered sugar twice.",
            "Make Italian meringue with sugar syrup at 118°C.",
            "Fold dry into meringue (macaronage) until ribbons form.",
            "Pipe rounds; rest 30 min until skinned.",
            "Bake at 150°C for 14 min.",
            "Sandwich with pistachio buttercream; mature 24 hours.",
        ],
        "nutrition": {"calories": 110, "protein": 2, "carbs": 13, "fat": 6, "fiber": 1, "sodium": 12, "gi": 65},
    },
    {
        "id": "cs-003", "title": "Sourdough Cinnamon Roll",
        "category": "chef-special", "country": "USA", "region": "Bakery",
        "image": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
        "video_url": "https://www.youtube.com/embed/B0hO63SH4pg",
        "cuisine": "Bakery", "difficulty": "Hard", "cook_time": 720, "servings": 8,
        "is_premium": True, "tier": "premium",
        "tags": ["vegetarian"],
        "description": "Slow-fermented sourdough cinnamon rolls with brown butter glaze.",
        "chef": {"name": "Chef Daniel Park", "credentials": "James Beard semi-finalist"},
        "ingredients": [
            ing("Bread flour", "500g", "flour"),
            ing("Active sourdough starter", "150g", "sourdough"),
            ing("Whole milk", "200ml", "milk"),
            ing("Butter", "80g", "butter"),
            ing("Brown sugar", "150g", "brown+sugar"),
            ing("Cinnamon", "2 tbsp", "cinnamon"),
            ing("Cream cheese", "120g", "cream+cheese"),
            ing("Powdered sugar", "100g", "sugar"),
        ],
        "steps": [
            "Mix flour, milk, starter, butter; bulk ferment 8 hours.",
            "Roll out; spread cinnamon-brown-sugar paste.",
            "Roll up tightly; cut into 8 rolls.",
            "Proof 2 hours.",
            "Bake at 180°C for 25 min.",
            "Glaze with cream cheese frosting while warm.",
        ],
        "nutrition": {"calories": 410, "protein": 8, "carbs": 58, "fat": 17, "fiber": 2, "sodium": 220, "gi": 70},
    },
    {
        "id": "cs-004", "title": "Mango Sticky Rice (Khao Niao Mamuang)",
        "category": "chef-special", "country": "Thailand", "region": "Royal Thai",
        "image": "https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=800",
        "video_url": "https://www.youtube.com/embed/AY79alHHWBQ",
        "cuisine": "Thai Dessert", "difficulty": "Easy", "cook_time": 40, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegan", "gluten-free", "dessert"],
        "description": "Thai street-side classic — coconut sticky rice with ripe mango.",
        "chef": {"name": "Chef Niran Tanasarn", "credentials": "Royal Thai Cuisine Master"},
        "ingredients": [
            ing("Glutinous rice", "300g", "rice"),
            ing("Coconut milk", "400ml", "coconut"),
            ing("Sugar", "80g", "sugar"),
            ing("Ripe mango", "2 large", "mango"),
            ing("Salt", "1/4 tsp", "salt"),
            ing("Sesame seeds", "1 tsp", "sesame"),
        ],
        "steps": [
            "Soak rice 4 hours; steam 25 min.",
            "Warm coconut milk with sugar and salt.",
            "Pour over rice; rest 20 min.",
            "Slice mango; serve with rice and sesame seeds.",
        ],
        "nutrition": {"calories": 420, "protein": 5, "carbs": 78, "fat": 11, "fiber": 3, "sodium": 110, "gi": 80},
    },
    {
        "id": "cs-005", "title": "Dark Chocolate Lava Cake",
        "category": "chef-special", "country": "France", "region": "Bistro",
        "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800",
        "video_url": "https://www.youtube.com/embed/Ckl1AEvkqww",
        "cuisine": "French Dessert", "difficulty": "Easy", "cook_time": 18, "servings": 4,
        "is_premium": False, "tier": "budget",
        "tags": ["vegetarian", "dessert"],
        "description": "Molten-center chocolate cake — a 12-minute showstopper.",
        "chef": {"name": "Chef Amélie Dubois", "credentials": "Le Cordon Bleu, Paris"},
        "ingredients": [
            ing("Dark chocolate (70%)", "200g", "chocolate"),
            ing("Butter", "100g", "butter"),
            ing("Eggs", "3", "egg"),
            ing("Egg yolk", "1", "egg+yolk"),
            ing("Sugar", "60g", "sugar"),
            ing("Flour", "30g", "flour"),
            ing("Vanilla", "1 tsp", "vanilla"),
        ],
        "steps": [
            "Melt chocolate and butter together.",
            "Whisk eggs, yolk, sugar, vanilla until pale.",
            "Fold chocolate mixture and flour together.",
            "Pour into buttered ramekins.",
            "Bake at 200°C for 10–12 min — center should jiggle.",
            "Invert and serve immediately.",
        ],
        "nutrition": {"calories": 510, "protein": 8, "carbs": 42, "fat": 35, "fiber": 4, "sodium": 80, "gi": 55},
    },
    {
        "id": "cs-006", "title": "Indian Gulab Jamun",
        "category": "chef-special", "country": "India", "region": "Royal Mughlai",
        "image": "https://images.unsplash.com/photo-1601303516534-bf91d5d63920?w=800",
        "video_url": "https://www.youtube.com/embed/RpI-VevW7-Q",
        "cuisine": "Indian Dessert", "difficulty": "Medium", "cook_time": 45, "servings": 6,
        "is_premium": True, "tier": "premium",
        "tags": ["vegetarian", "dessert"],
        "description": "Saffron-rose syrup dumplings — celebration sweet across the subcontinent.",
        "chef": {"name": "Chef Rashmi Verma", "credentials": "Heritage Indian Sweets"},
        "ingredients": [
            ing("Khoya/Mawa", "200g", "milk+solids"),
            ing("All-purpose flour", "30g", "flour"),
            ing("Baking soda", "1/8 tsp", "baking+soda"),
            ing("Milk", "2 tbsp", "milk"),
            ing("Ghee for frying", "500ml", "ghee"),
            ing("Sugar", "400g", "sugar"),
            ing("Cardamom pods", "4", "cardamom"),
            ing("Saffron", "pinch", "saffron"),
            ing("Rose water", "1 tsp", "rose"),
        ],
        "steps": [
            "Make sugar syrup with cardamom, saffron, rose water; keep warm.",
            "Knead khoya, flour, soda, milk into smooth dough.",
            "Form small balls (no cracks).",
            "Fry in low-medium ghee until golden.",
            "Soak in warm syrup 2 hours.",
        ],
        "nutrition": {"calories": 380, "protein": 6, "carbs": 64, "fat": 12, "fiber": 0, "sodium": 60, "gi": 75},
    },
]


def _apply_healthcare_enrichments():
    """One-time merge: pull ENRICHMENTS + EXTRA_RECIPES from healthcare_data."""
    try:
        from healthcare_data import ENRICHMENTS, EXTRA_RECIPES
    except Exception:
        return
    # Enrich existing recipes
    for r in RECIPES:
        e = ENRICHMENTS.get(r["id"])
        if e:
            r.update(e)
    # Append extras (with their inline _enrichment merged in)
    existing_ids = {r["id"] for r in RECIPES}
    for extra in EXTRA_RECIPES:
        if extra["id"] in existing_ids:
            continue
        merged = {**extra}
        enr = merged.pop("_enrichment", {})
        merged.update(enr)
        RECIPES.append(merged)


_apply_healthcare_enrichments()


def get_all_recipes():
    return RECIPES


def get_recipe(recipe_id):
    return next((r for r in RECIPES if r["id"] == recipe_id), None)


def get_recipes_by_category(category):
    return [r for r in RECIPES if r["category"] == category]
